// Document template library (master build instruction §27). Template TYPES with structured placeholders, not legal
// conclusions: every legal template starts "DRAFT — COUNSEL REVIEW REQUIRED" until an owner records counsel's approval.
// Empty placeholders render as [TO CONFIRM: …] so a gap can never pass silently. Reports are built from records.

export type TemplateField = { key: string; label: string; area?: boolean };
export type TemplateDef = {
  key: string; name: string; group: "Confidentiality" | "Engagement" | "Introducers and partners" | "Capital" | "Information" | "Reports" | "Commercial";
  legal: boolean; entity: "project" | "organization" | "broker" | "deal" | "objective" | "none"; fields: TemplateField[]; body: string;
};

const F = (key: string, label: string, area = false): TemplateField => ({ key, label, area });
const PARTIES = [F("counterparty", "Counterparty (legal name)"), F("counterpartyAddress", "Counterparty address"), F("counterpartySignatory", "Counterparty signatory, title"), F("regeneraSignatory", "Regenera signatory, title"), F("effectiveDate", "Effective date"), F("governingLaw", "Governing law and forum")];
const SIGN = `\n## Signatures\n**Regenera:** {{regeneraSignatory}}\n\n**{{counterparty}}:** {{counterpartySignatory}}`;
const BOILER = `\n## General\n- This document is a template prepared for review by qualified counsel in the relevant jurisdiction. Nothing in it is legal, tax or investment advice.\n- Governing law and forum: {{governingLaw}}.\n- Notices in writing to the addresses above.`;

export const TEMPLATES: TemplateDef[] = [
  { key: "mutual-nda", name: "Mutual NDA", group: "Confidentiality", legal: true, entity: "organization", fields: [...PARTIES, F("purpose", "Purpose of the disclosure"), F("term", "Term (months)")],
    body: `# Mutual Non-Disclosure Agreement\nBetween Regenera and {{counterparty}} ({{counterpartyAddress}}), effective {{effectiveDate}}.\n## Purpose\n{{purpose}}\n## Confidential information\nAll non-public information disclosed by either party for the Purpose, in any form, marked or reasonably understood as confidential.\n## Obligations\n- Use only for the Purpose; protect with at least reasonable care.\n- Disclose only to representatives who need to know and are bound by equivalent duties.\n- Return or destroy on request, subject to legal retention.\n## Exclusions\nInformation that is public, already known, independently developed, or lawfully received from a third party.\n## Term\n{{term}} months from the effective date; obligations survive for the period counsel confirms.\n## No offer\nNothing in this agreement is an offer of securities, a commitment to transact or a licence.${BOILER}${SIGN}` },
  { key: "one-way-nda", name: "One-way NDA", group: "Confidentiality", legal: true, entity: "organization", fields: [...PARTIES, F("discloser", "Disclosing party"), F("purpose", "Purpose")],
    body: `# Confidentiality Undertaking (one-way)\n{{counterparty}} undertakes to keep confidential the information disclosed by {{discloser}} for: {{purpose}}.\n## Undertakings\n- Use only for the stated purpose.\n- No disclosure except to advisers bound by equivalent duties.\n- Return or destroy on request.\n## No offer\nNothing here is an offer of securities or investment advice.${BOILER}${SIGN}` },
  { key: "advisory-engagement", name: "Advisory Engagement Letter", group: "Engagement", legal: true, entity: "organization", fields: [...PARTIES, F("scope", "Scope of services", true), F("fees", "Fees and invoicing"), F("term", "Term")],
    body: `# Advisory Engagement Letter\n## Scope\n{{scope}}\n## Fees\n{{fees}}\n## Term\n{{term}}\n## What Regenera does not do\nRegenera does not act as a broker-dealer, placement agent, investment adviser, legal, tax or engineering adviser unless separately licensed and engaged for that role in writing.\n## Success-based compensation\nAny success-based or capital-linked compensation requires compliance review before signature.${BOILER}${SIGN}` },
  { key: "sponsor-engagement", name: "Project Sponsor Engagement", group: "Engagement", legal: true, entity: "project", fields: [...PARTIES, F("project", "Project"), F("scope", "Scope", true), F("fees", "Fees")],
    body: `# Project Sponsor Engagement\nProject: {{project}}.\n## Scope\n{{scope}}\n## Sponsor responsibilities\n- Provide accurate information and documents on request; Regenera labels sponsor information as Sponsor provided until verified.\n- Keep Regenera informed of material changes.\n## Fees\n{{fees}}${BOILER}${SIGN}` },
  { key: "development-scope", name: "Project Development Scope", group: "Engagement", legal: false, entity: "project", fields: [F("project", "Project"), F("workstreams", "Workstreams", true), F("deliverables", "Deliverables", true), F("timeline", "Timeline"), F("assumptions", "Assumptions", true)],
    body: `# Project Development Scope: {{project}}\n## Workstreams\n{{workstreams}}\n## Deliverables\n{{deliverables}}\n## Timeline\n{{timeline}}\n## Assumptions and exclusions\n{{assumptions}}` },
  { key: "capital-advisory-scope", name: "Capital Advisory Scope", group: "Engagement", legal: true, entity: "project", fields: [...PARTIES, F("project", "Project"), F("scope", "Scope", true), F("jurisdictions", "Offering jurisdictions")],
    body: `# Capital Advisory Scope: {{project}}\n## Scope\n{{scope}}\n## Regulatory boundary\nCapital introductions and any offering in {{jurisdictions}} are subject to the applicable securities rules; Regenera acts only within roles it is permitted to perform, and regulated activities are carried out by appropriately licensed parties.\n## Compensation\nCOMPLIANCE REVIEW REQUIRED before any success-based term is agreed.${BOILER}${SIGN}` },
  { key: "referral-agreement", name: "Broker / Referral Agreement", group: "Introducers and partners", legal: true, entity: "broker", fields: [...PARTIES, F("role", "Introducer role"), F("territory", "Territory / jurisdictions"), F("fee", "Referral fee terms"), F("protection", "Protection period")],
    body: `# Referral Agreement\n{{counterparty}} ("Introducer") acting as {{role}} in {{territory}}.\n## Registration\nAn introduction qualifies only if registered in the Regenera introducer portal and approved in writing before it is made. Registration alone creates no entitlement.\n## Fee\n{{fee}} — ESTIMATED / SUBJECT TO AGREEMENT until this agreement is executed and legal review is approved.\n## Protection period\n{{protection}}\n## Restrictions\n- The Introducer does not offer, negotiate or advise on securities unless licensed to do so and approved by Regenera for that role.\n- Only materials approved for distribution to introducers may be shared.\n- Compliance with anti-bribery, sanctions and data protection laws.${BOILER}${SIGN}` },
  { key: "introducer-agreement", name: "Introducer Agreement", group: "Introducers and partners", legal: true, entity: "broker", fields: [...PARTIES, F("scope", "Introduction scope", true), F("fee", "Fee terms")],
    body: `# Introducer Agreement\n## Scope\n{{scope}}\n## Fee\n{{fee}} — subject to execution and legal review.\n## No authority\nThe Introducer has no authority to bind Regenera or to make representations about any investment.${BOILER}${SIGN}` },
  { key: "partner-mou", name: "Partner MOU", group: "Introducers and partners", legal: true, entity: "organization", fields: [...PARTIES, F("objectives", "Shared objectives", true), F("contributions", "Contributions of each party", true)],
    body: `# Memorandum of Understanding\n## Objectives\n{{objectives}}\n## Contributions\n{{contributions}}\n## Non-binding\nThis MOU records intentions and is not legally binding except for confidentiality and costs.${BOILER}${SIGN}` },
  { key: "collaboration-agreement", name: "Collaboration Agreement", group: "Introducers and partners", legal: true, entity: "organization", fields: [...PARTIES, F("scope", "Scope", true), F("ip", "Intellectual property")],
    body: `# Collaboration Agreement\n## Scope\n{{scope}}\n## Intellectual property\n{{ip}}${BOILER}${SIGN}` },
  { key: "consultant-sow", name: "Consultant SOW", group: "Introducers and partners", legal: true, entity: "organization", fields: [...PARTIES, F("project", "Project"), F("services", "Services", true), F("deliverables", "Deliverables", true), F("price", "Price and payment")],
    body: `# Statement of Work: {{project}}\n## Services\n{{services}}\n## Deliverables\n{{deliverables}}\n## Price and payment\n{{price}}\n## E&S requirements\nThe consultant complies with the project's environmental, social, labour and OHS requirements flowed down by Regenera.${BOILER}${SIGN}` },
  { key: "epc-introduction", name: "EPC / Technical Partner Introduction", group: "Introducers and partners", legal: false, entity: "project", fields: [F("project", "Project"), F("partner", "Partner"), F("why", "Why this partner", true), F("next", "Proposed next step")],
    body: `# Introduction: {{partner}} for {{project}}\n## Why\n{{why}}\n## Proposed next step\n{{next}}\n> Introductions carry no commitment by any party.` },
  { key: "data-room-access", name: "Data Room Access Agreement", group: "Confidentiality", legal: true, entity: "organization", fields: [...PARTIES, F("dataRoom", "Data room"), F("permitted", "Permitted use")],
    body: `# Data Room Access Agreement\nAccess to {{dataRoom}} for: {{permitted}}.\n## Conditions\n- Access is personal, logged and revocable.\n- No download, forwarding or copying beyond what the room permits.\n- Information is confidential and not an offer of securities.${BOILER}${SIGN}` },
  { key: "qualification-attestation", name: "Investor Qualification Attestation", group: "Capital", legal: true, entity: "organization", fields: [...PARTIES, F("jurisdiction", "Jurisdiction"), F("category", "Qualification category (as defined in that jurisdiction)"), F("basis", "Basis for qualification", true)],
    body: `# Investor Qualification Attestation\nJurisdiction: {{jurisdiction}}. Category: {{category}}.\n## Basis\n{{basis}}\n## Important\nQualification categories differ by jurisdiction and rule. This attestation is recorded with its evidence and expiry; it may need independent verification before any offering material is shared.${BOILER}${SIGN}` },
  { key: "conflict-disclosure", name: "Conflict Disclosure", group: "Capital", legal: true, entity: "none", fields: [F("parties", "Parties"), F("conflict", "Nature of the conflict", true), F("mitigation", "How it is managed", true)],
    body: `# Conflict of Interest Disclosure\n## Parties\n{{parties}}\n## Conflict\n{{conflict}}\n## Management\n{{mitigation}}` },
  { key: "information-request", name: "Project Information Request", group: "Information", legal: false, entity: "project", fields: [F("project", "Project"), F("items", "Information requested (one per line)", true), F("dueDate", "Requested by")],
    body: `# Project Information Request: {{project}}\nPlease share the following by {{dueDate}} through the sponsor portal:\n{{items}}\n> Where a document does not exist yet, say so; unknowns are recorded as unknown, not assumed.` },
  { key: "loi", name: "Letter of Intent", group: "Capital", legal: true, entity: "organization", fields: [...PARTIES, F("transaction", "Proposed transaction", true), F("conditions", "Conditions", true), F("exclusivity", "Exclusivity (if any)")],
    body: `# Letter of Intent (non-binding)\n## Proposed transaction\n{{transaction}}\n## Conditions\n{{conditions}}\n## Exclusivity\n{{exclusivity}}\n## Non-binding\nThis letter is not binding except for confidentiality, exclusivity (if any) and costs.${BOILER}${SIGN}` },
  { key: "term-sheet", name: "Non-binding Term Sheet", group: "Capital", legal: true, entity: "project", fields: [...PARTIES, F("project", "Project"), F("instrument", "Instrument"), F("amount", "Amount and currency"), F("pricing", "Pricing / return"), F("tenor", "Tenor"), F("security", "Security"), F("conditions", "Conditions precedent", true)],
    body: `# Indicative Term Sheet: {{project}}\n- **Instrument:** {{instrument}}\n- **Amount:** {{amount}}\n- **Pricing:** {{pricing}}\n- **Tenor:** {{tenor}}\n- **Security:** {{security}}\n## Conditions precedent\n{{conditions}}\n## Non-binding\nIndicative only; subject to due diligence, approvals, documentation and applicable securities law.${BOILER}${SIGN}` },
  { key: "meeting-memo", name: "Meeting Memo", group: "Information", legal: false, entity: "none", fields: [F("meeting", "Meeting"), F("date", "Date"), F("attendees", "Attendees"), F("discussion", "Discussion", true), F("actions", "Actions (owner, date)", true)],
    body: `# Meeting memo: {{meeting}}\n{{date}} · {{attendees}}\n## Discussion\n{{discussion}}\n## Actions\n{{actions}}` },
  { key: "investor-teaser", name: "Investor Teaser", group: "Capital", legal: false, entity: "project", fields: [F("project", "Project"), F("summary", "Summary", true), F("ask", "Capital sought (instrument, amount)"), F("highlights", "Highlights (sourced)", true), F("risks", "Key risks", true)],
    body: `# {{project}}\n> Distribution only under an approved distribution rule; not an offer of securities.\n## Summary\n{{summary}}\n## Capital sought\n{{ask}}\n## Highlights\n{{highlights}}\n## Key risks\n{{risks}}` },
  { key: "investment-memo", name: "Investment Memo", group: "Capital", legal: false, entity: "project", fields: [F("project", "Project"), F("thesis", "Thesis", true), F("structure", "Structure", true), F("risks", "Risks and mitigants", true), F("recommendation", "Recommendation (requires approval)")],
    body: `# Investment memo: {{project}}\n## Thesis\n{{thesis}}\n## Structure\n{{structure}}\n## Risks and mitigants\n{{risks}}\n## Recommendation\n{{recommendation}}\n> Human approval required before this memo is shared or relied on.` },
  { key: "project-brief", name: "Project Brief", group: "Reports", legal: false, entity: "project", fields: [], body: "" },
  { key: "site-intelligence-report", name: "Site Intelligence Report", group: "Reports", legal: false, entity: "project", fields: [], body: "" },
  { key: "capital-pathway-report", name: "Capital Pathway Report", group: "Reports", legal: false, entity: "project", fields: [], body: "" },
  { key: "systems-assessment-report", name: "Systems Assessment", group: "Reports", legal: false, entity: "project", fields: [], body: "" },
  { key: "monthly-update", name: "Monthly Project Update", group: "Reports", legal: false, entity: "project", fields: [], body: "" },
  { key: "commission-statement", name: "Commission Statement", group: "Reports", legal: false, entity: "broker", fields: [], body: "" },
  // Commercial documents built from records (lib/documents/commercial.ts), opened from a record's Generate menu.
  { key: "account-brief", name: "Account brief", group: "Commercial", legal: false, entity: "organization", fields: [], body: "" },
  { key: "meeting-brief", name: "Meeting brief", group: "Commercial", legal: false, entity: "organization", fields: [], body: "" },
  { key: "opportunity-shortlist", name: "Opportunity / partner shortlist", group: "Commercial", legal: false, entity: "objective", fields: [], body: "" },
  { key: "capital-matching-brief", name: "Capital matching brief", group: "Commercial", legal: false, entity: "objective", fields: [], body: "" },
  { key: "bid-no-bid", name: "Bid / no-bid memo", group: "Commercial", legal: false, entity: "deal", fields: [], body: "" },
  { key: "proposal", name: "Proposal (from the offer catalogue)", group: "Commercial", legal: false, entity: "deal", fields: [], body: "" },
];

/** Replaces {{placeholders}}; anything empty becomes [TO CONFIRM: label]. */
export function fillTemplate(t: TemplateDef, values: Record<string, string>) {
  const label = (k: string) => t.fields.find(f => f.key === k)?.label ?? k;
  return t.body.replace(/\{\{(\w+)\}\}/g, (_, k: string) => (values[k]?.trim() ? values[k].trim() : `[TO CONFIRM: ${label(k)}]`));
}
export const openPlaceholders = (md: string) => [...md.matchAll(/\[TO CONFIRM: ([^\]]+)\]/g)].map(m => m[1]);
