// Data-driven reports (master build instruction §64). Each states report date, data freshness, sources, unknowns,
// assumptions, generator and approval state. Built from records only; nothing is inferred into a fact.
import { and, asc, desc, eq, gte } from "drizzle-orm";
import type { Db } from "@/db";
import {
  brokerProfiles, capitalOpportunities, capitalRequirements, capitalTranches, commissionEvents, decisions, interventions, placeFacts, portalUsers, projectMilestones,
  projects, projectUpdates, referralRegistrations, studies, systemAssessments,
} from "@/db/schema";
import { studyGaps } from "@/lib/delivery/engine";
import { STUDY_TYPES } from "@/lib/delivery/vocab";
import { PLACE_DIMENSIONS, PLACE_GAPS } from "@/lib/place/engine";
import { COMMISSION_STATUSES, REFERRAL_STATUSES } from "@/lib/portal/vocab";
import { projectBriefMarkdown } from "@/lib/projects/brief";
import { compactMoney, stageLabel } from "@/lib/projects/labels";
import { CAPITAL_STATUSES, INSTRUMENTS } from "@/lib/projects/vocab";
import { CAPACITY_LABELS, INTERVENTION_STATUSES, SYSTEM_CATEGORIES } from "@/lib/systems/vocab";

const footer = (today: string, sources: string[], unknowns: string[], assumptions: string[]) => [
  "", "## About this report",
  `- Report date: ${today}. Generated by Regenera OS from its records; approval state is shown in the footer.`,
  `- Sources: ${sources.length ? sources.join("; ") : "records entered in Regenera OS"}.`,
  `- Unknowns: ${unknowns.length ? unknowns.join("; ") : "none recorded"}.`,
  `- Assumptions: ${assumptions.length ? assumptions.join("; ") : "none"}.`,
  "- Not legal, engineering, tax or investment advice.",
].join("\n");

export async function reportMarkdown(db: Db, key: string, entityId: string, today: string): Promise<{ title: string; md: string } | null> {
  if (key === "project-brief") return projectBriefMarkdown(db, entityId, today);
  if (key === "commission-statement") {
    const [b] = await db.select({ b: brokerProfiles, name: portalUsers.name, email: portalUsers.email }).from(brokerProfiles).innerJoin(portalUsers, eq(portalUsers.id, brokerProfiles.portalUserId)).where(eq(brokerProfiles.id, entityId));
    if (!b) return null;
    const regs = await db.select().from(referralRegistrations).where(eq(referralRegistrations.brokerId, b.b.id)).orderBy(desc(referralRegistrations.createdAt));
    const ev = await db.select().from(commissionEvents).where(eq(commissionEvents.brokerId, b.b.id)).orderBy(desc(commissionEvents.createdAt));
    const title = `Commission statement: ${b.name || b.email}`;
    return { title, md: [`# ${title}`, "", `Agreement: ${b.b.agreementStatus}${b.b.agreementExpiresAt ? ` to ${b.b.agreementExpiresAt}` : ""} · status ${b.b.complianceStatus}`, "",
      "## Registrations", ...(regs.length ? regs.map(r => `- ${r.name}${r.organization ? ` (${r.organization})` : ""}: ${REFERRAL_STATUSES[r.status]}${r.expiresAt ? `, protected to ${r.expiresAt}` : ""}`) : ["None."]), "",
      "## Fees", ...(ev.length ? ev.map(e => `- ${compactMoney(e.amount, e.currency)}${e.basisAmount !== null ? ` on ${compactMoney(e.basisAmount, e.currency)}` : ""}: **${e.status === "estimated" ? "ESTIMATED / SUBJECT TO AGREEMENT" : COMMISSION_STATUSES[e.status]}**${e.paidAt ? `, paid ${e.paidAt.slice(0, 10)}` : ""}`) : ["None."]),
      footer(today, ["introducer registrations and commission ledger"], [], ["Estimated amounts are arithmetic on the recorded schedule; entitlement depends on the executed agreement"])].join("\n") };
  }
  const [p] = await db.select().from(projects).where(eq(projects.id, entityId));
  if (!p) return null;
  if (key === "site-intelligence-report") {
    const facts = await db.select().from(placeFacts).where(eq(placeFacts.projectId, p.id)).orderBy(asc(placeFacts.dimension));
    const st = await db.select({ type: studies.type, status: studies.status }).from(studies).where(eq(studies.projectId, p.id));
    const g = studyGaps(p, st);
    const latest = facts.reduce<string | null>((a, f) => (!a || f.retrievedAt > a ? f.retrievedAt : a), null);
    const title = `Site intelligence: ${p.name}`;
    return { title, md: [`# ${title}`, "", `**Location:** ${[p.municipality, p.subdivision, p.country].filter(Boolean).join(", ") || "not recorded"}${p.lat !== null ? ` (${p.lat}, ${p.lng})` : ""} · **Data retrieved:** ${latest?.slice(0, 10) ?? "no place profile yet"}`, "",
      ...(Object.keys(PLACE_DIMENSIONS) as (keyof typeof PLACE_DIMENSIONS)[]).flatMap(d => {
        const rows = facts.filter(f => f.dimension === d);
        return [`## ${PLACE_DIMENSIONS[d]}`, ...(rows.length ? rows.map(f => `- ${f.label}: ${f.value} (${f.integrationKey}, tier ${f.tier}, ${f.retrievedAt.slice(0, 10)}${f.state === "stale" ? ", stale" : ""})`) : ["- No sourced facts yet."]), ...PLACE_GAPS[d].map(x => `- Unknown: ${x}`), ""];
      }),
      "## Studies", `Expected: ${g.expected.map(t => STUDY_TYPES[t]).join(", ")}. Missing: ${g.missing.map(t => STUDY_TYPES[t]).join(", ") || "none"}.`,
      footer(today, [...new Set(facts.map(f => `${f.integrationKey} (${f.license ?? "licence per registry"})`))], ["see Unknown lines above"], ["Public datasets describe context, not a site assessment"])].join("\n") };
  }
  if (key === "capital-pathway-report") {
    const reqs = await db.select().from(capitalRequirements).where(eq(capitalRequirements.projectId, p.id)).orderBy(asc(capitalRequirements.targetClose));
    const tr = await db.select().from(capitalTranches).where(eq(capitalTranches.projectId, p.id));
    const opps = await db.select().from(capitalOpportunities).where(eq(capitalOpportunities.projectId, p.id));
    const title = `Capital pathway: ${p.name}`;
    const total = new Map<string, number>();
    for (const r of reqs.filter(x => x.status !== "cancelled")) total.set(r.currency, (total.get(r.currency) ?? 0) + (r.target ?? 0));
    return { title, md: [`# ${title}`, "", `**Stage:** ${stageLabel(p.stage)} · **CAPEX:** ${compactMoney(p.capex, p.currency ?? "USD")} · **Requirements total:** ${[...total].map(([c, v]) => compactMoney(v, c)).join(" + ") || "none"}`, "",
      "## Capital stack", ...(reqs.length ? reqs.flatMap(r => [`- **${r.purpose}** · ${INSTRUMENTS[r.instrument]} · ${compactMoney(r.target, r.currency)}${r.target && total.get(r.currency) ? ` (${Math.round(((r.target ?? 0) / (total.get(r.currency) ?? 1)) * 100)}%)` : ""} · secured ${compactMoney(r.secured, r.currency)} · ${CAPITAL_STATUSES[r.status]}${r.targetClose ? ` · close ${r.targetClose}` : ""}${r.economics ? ` · ${r.economics}` : ""}`, ...tr.filter(t => t.requirementId === r.id).map(t => `  - Tranche ${t.name}: ${compactMoney(t.target, t.currency)}${t.targetInvestorType ? ` for ${t.targetInvestorType}` : ""}`)]) : ["No capital requirements recorded."]), "",
      "## Capital opportunities", ...(opps.length ? opps.map(o => `- ${o.title}: gate ${o.gateState.replace(/_/g, " ")}, ${o.status}${o.jurisdictions.length ? `, jurisdictions ${o.jurisdictions.join(", ")}` : ""}`) : ["None yet."]),
      footer(today, ["capital requirements, tranches and opportunities recorded in the OS"], reqs.filter(r => r.target === null).map(r => `target for ${r.purpose}`), ["Commercial fit and legal eligibility are assessed separately; no structure is represented as legally compliant without review"])].join("\n") };
  }
  if (key === "systems-assessment-report") {
    const as = await db.select().from(systemAssessments).where(eq(systemAssessments.projectId, p.id));
    const ints = await db.select().from(interventions).where(eq(interventions.projectId, p.id));
    const title = `Systems assessment: ${p.name}`;
    return { title, md: [`# ${title}`, "",
      ...(Object.keys(SYSTEM_CATEGORIES) as (keyof typeof SYSTEM_CATEGORIES)[]).flatMap(c => {
        const a = as.find(x => x.category === c);
        if (!a) return [`## ${SYSTEM_CATEGORIES[c]}`, "Not assessed.", ""];
        return [`## ${SYSTEM_CATEGORIES[c]}: ${CAPACITY_LABELS[a.capacity]}${a.status === "reviewed" ? ` (reviewed by ${a.reviewer})` : " (draft)"}`, ...[["Baseline", a.baseline], ["Dependencies", a.dependencies], ["Impacts", a.impacts], ["Thresholds", a.thresholds], ["Risks", a.risks], ["Opportunities", a.opportunities], ["Future state", a.futureState]].filter(([, v]) => v).map(([k, v]) => `- **${k}:** ${v}`), ...Object.entries(a.implications).map(([k, v]) => `- Implication (${k}): ${v}`), a.sources ? `- Sources: ${a.sources}` : "- Sources: not recorded", ""];
      }),
      "## Interventions", ...(ints.length ? ints.map(i => `- ${i.systemIssue}: ${compactMoney(i.costEstimate, i.currency)}${i.costBasis ? ` (${i.costBasis})` : ""} · ${INTERVENTION_STATUSES[i.status]}${i.fundingPathway ? ` · funding: ${i.fundingPathway}` : ""}`) : ["None recorded."]),
      footer(today, [...new Set(as.map(a => a.sources).filter(Boolean))], Object.keys(SYSTEM_CATEGORIES).filter(c => !as.some(a => a.category === c)).map(c => `${SYSTEM_CATEGORIES[c as keyof typeof SYSTEM_CATEGORIES]} not assessed`), ["Framework mappings (TNFD, IFC PS, ISSB) are references, not certifications"])].join("\n") };
  }
  if (key === "monthly-update") {
    const since = new Date(Date.parse(today) - 31 * 86_400_000).toISOString().slice(0, 10);
    const ms = await db.select().from(projectMilestones).where(eq(projectMilestones.projectId, p.id)).orderBy(asc(projectMilestones.dueDate));
    const ds = await db.select().from(decisions).where(and(eq(decisions.projectId, p.id), gte(decisions.updatedAt, since)));
    const ups = await db.select().from(projectUpdates).where(and(eq(projectUpdates.projectId, p.id), gte(projectUpdates.createdAt, since)));
    const title = `Monthly update: ${p.name}`;
    const done = ms.filter(m => m.status === "done" && (m.completedAt ?? "") >= since);
    return { title, md: [`# ${title}`, "", `**Stage:** ${stageLabel(p.stage)} since ${p.stageChangedAt.slice(0, 10)}`, "",
      "## Completed this month", ...(done.length ? done.map(m => `- ${m.name} (${m.completedAt})`) : ["None recorded."]),
      "", "## Coming up", ...(ms.filter(m => m.status !== "done" && m.status !== "cancelled").slice(0, 8).map(m => `- ${m.name}${m.dueDate ? ` (due ${m.dueDate})` : ""}`)), "",
      "## Decisions", ...(ds.length ? ds.map(d => `- ${d.title}: ${d.status}${d.decision ? `, ${d.decision}` : ""}`) : ["None."]), "",
      "## Updates shared", ...(ups.length ? ups.map(u => `- ${u.title}${u.publishedAt ? ` (published ${u.publishedAt.slice(0, 10)})` : " (draft)"}`) : ["None."]),
      footer(today, ["milestones, decisions and updates recorded in the OS"], [], ["For external audiences, publish through an approved project update"])].join("\n") };
  }
  return null;
}
