CREATE TABLE `communities` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text,
	`name` text NOT NULL,
	`preferred_name` text DEFAULT '' NOT NULL,
	`people_nation_group` text DEFAULT '' NOT NULL,
	`community_type` text DEFAULT 'local' NOT NULL,
	`country` text,
	`jurisdiction` text DEFAULT '' NOT NULL,
	`region` text DEFAULT '' NOT NULL,
	`territory_name` text DEFAULT '' NOT NULL,
	`administrative_area` text DEFAULT '' NOT NULL,
	`language_primary` text DEFAULT '' NOT NULL,
	`languages_other` text DEFAULT '[]' NOT NULL,
	`population_estimate` integer,
	`representative_body` text DEFAULT '' NOT NULL,
	`recognized_authority` text DEFAULT '' NOT NULL,
	`customary_authority` text DEFAULT '' NOT NULL,
	`legal_entity_name` text DEFAULT '' NOT NULL,
	`legal_entity_type` text DEFAULT '' NOT NULL,
	`land_relationship` text DEFAULT '' NOT NULL,
	`tenure_type` text DEFAULT '' NOT NULL,
	`customary_rights_status` text DEFAULT 'unknown' NOT NULL,
	`statutory_rights_status` text DEFAULT 'unknown' NOT NULL,
	`resource_rights_status` text DEFAULT 'unknown' NOT NULL,
	`cultural_rights_status` text DEFAULT 'unknown' NOT NULL,
	`known_disputes` text DEFAULT '' NOT NULL,
	`representation_verified` integer DEFAULT false NOT NULL,
	`authority_verified` integer DEFAULT false NOT NULL,
	`verification_source` text DEFAULT '' NOT NULL,
	`primary_contact_id` text,
	`org_id` text,
	`area_geometry` text,
	`area_generalized` integer DEFAULT true NOT NULL,
	`local_contexts` text DEFAULT '{}' NOT NULL,
	`is_demo` integer DEFAULT false NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `communities_project` ON `communities` (`project_id`);--> statement-breakpoint
CREATE INDEX `communities_mandate` ON `communities` (`mandate_id`);--> statement-breakpoint
CREATE TABLE `community_authorities` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`community_id` text NOT NULL,
	`name` text NOT NULL,
	`authority_type` text NOT NULL,
	`individual_or_body` text DEFAULT 'body' NOT NULL,
	`scope` text DEFAULT '' NOT NULL,
	`subjects_authorized` text DEFAULT '' NOT NULL,
	`subjects_not_authorized` text DEFAULT '' NOT NULL,
	`basis` text DEFAULT '' NOT NULL,
	`geographic_scope` text DEFAULT '' NOT NULL,
	`term_start` text,
	`term_end` text,
	`powers` text DEFAULT '[]' NOT NULL,
	`knowledge_categories` text DEFAULT '[]' NOT NULL,
	`verification_status` text DEFAULT 'unverified' NOT NULL,
	`verified_by` text,
	`documentation` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `community_authorities_community` ON `community_authorities` (`community_id`);--> statement-breakpoint
CREATE TABLE `community_commitments` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`community_id` text,
	`source` text DEFAULT '' NOT NULL,
	`agreement_id` text,
	`engagement_id` text,
	`type` text NOT NULL,
	`description` text NOT NULL,
	`owner` text,
	`beneficiary` text DEFAULT '' NOT NULL,
	`start_date` text,
	`due_date` text,
	`recurrence` text DEFAULT 'none' NOT NULL,
	`amount` real,
	`currency` text DEFAULT 'USD' NOT NULL,
	`indexed` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'proposed' NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`verification_required` integer DEFAULT false NOT NULL,
	`verified_by` text,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `community_commitments_project` ON `community_commitments` (`project_id`,`status`);--> statement-breakpoint
CREATE TABLE `community_engagements` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text,
	`community_id` text NOT NULL,
	`date` text NOT NULL,
	`location` text DEFAULT '' NOT NULL,
	`format` text DEFAULT 'meeting' NOT NULL,
	`participants` text DEFAULT '' NOT NULL,
	`project_team` text DEFAULT '' NOT NULL,
	`facilitator` text DEFAULT '' NOT NULL,
	`interpreter` text DEFAULT '' NOT NULL,
	`topics` text DEFAULT '' NOT NULL,
	`concerns` text DEFAULT '' NOT NULL,
	`requests` text DEFAULT '' NOT NULL,
	`commitments_made` text DEFAULT '' NOT NULL,
	`decision_status` text DEFAULT '' NOT NULL,
	`community_review_status` text DEFAULT 'not_shared' NOT NULL,
	`next_action` text DEFAULT '' NOT NULL,
	`owner` text,
	`due_date` text,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `community_engagements_community` ON `community_engagements` (`community_id`,`date`);--> statement-breakpoint
CREATE TABLE `community_funds` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text,
	`community_id` text NOT NULL,
	`name` text NOT NULL,
	`legal_vehicle` text DEFAULT '' NOT NULL,
	`governance_body` text DEFAULT '' NOT NULL,
	`beneficiaries` text DEFAULT '' NOT NULL,
	`allocation_policy` text DEFAULT '[]' NOT NULL,
	`investment_policy` text DEFAULT '' NOT NULL,
	`spending_policy` text DEFAULT '' NOT NULL,
	`reserve_policy` text DEFAULT '' NOT NULL,
	`audit_requirement` text DEFAULT '' NOT NULL,
	`reporting_frequency` text DEFAULT '' NOT NULL,
	`trustee` text DEFAULT '' NOT NULL,
	`custodian` text DEFAULT '' NOT NULL,
	`balance` real,
	`currency` text DEFAULT 'USD' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `community_governance_rights` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`community_id` text NOT NULL,
	`right_type` text NOT NULL,
	`governing_document` text DEFAULT '' NOT NULL,
	`scope` text DEFAULT '' NOT NULL,
	`trigger` text DEFAULT '' NOT NULL,
	`approval_required` integer DEFAULT false NOT NULL,
	`information_access` text DEFAULT '' NOT NULL,
	`voting_threshold` text DEFAULT '' NOT NULL,
	`duration` text DEFAULT '' NOT NULL,
	`scenario` text DEFAULT 'Base' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `community_grievances` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`community_id` text,
	`received` text NOT NULL,
	`channel` text DEFAULT '' NOT NULL,
	`summary` text NOT NULL,
	`category` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'received' NOT NULL,
	`owner` text,
	`response` text DEFAULT '' NOT NULL,
	`resolved_at` text,
	`confidential` integer DEFAULT true NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `community_ledger` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`community_id` text NOT NULL,
	`structure_id` text,
	`ledger` text NOT NULL,
	`category` text NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`amount` real NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`date` text NOT NULL,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `community_ledger_project` ON `community_ledger` (`project_id`,`ledger`);--> statement-breakpoint
CREATE TABLE `community_rights` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`community_id` text NOT NULL,
	`project_id` text,
	`right_type` text NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`legal_basis` text DEFAULT '' NOT NULL,
	`customary_basis` text DEFAULT '' NOT NULL,
	`geographic_scope` text DEFAULT '' NOT NULL,
	`spatial_ref` text,
	`source_document` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'asserted' NOT NULL,
	`verified_by` text,
	`verification_date` text,
	`affected_stage` text DEFAULT '' NOT NULL,
	`materiality` text DEFAULT 'unknown' NOT NULL,
	`mitigation_required` integer DEFAULT false NOT NULL,
	`consent_required` integer DEFAULT false NOT NULL,
	`compensation_required` integer DEFAULT false NOT NULL,
	`negotiation_required` integer DEFAULT false NOT NULL,
	`resolution` text DEFAULT 'open' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `community_rights_community` ON `community_rights` (`community_id`);--> statement-breakpoint
CREATE TABLE `consent_records` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text,
	`community_id` text NOT NULL,
	`knowledge_record_id` text,
	`consent_type` text DEFAULT 'fpic' NOT NULL,
	`consent_required` integer DEFAULT true NOT NULL,
	`authority_id` text,
	`status` text DEFAULT 'not_started' NOT NULL,
	`scope` text DEFAULT '' NOT NULL,
	`disclosures` text DEFAULT '{}' NOT NULL,
	`language_used` text DEFAULT '' NOT NULL,
	`interpreter` text DEFAULT '' NOT NULL,
	`method` text DEFAULT '' NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`conditions` text DEFAULT '' NOT NULL,
	`consent_date` text,
	`expiry_date` text,
	`review_date` text,
	`withdrawal_mechanism` text DEFAULT '' NOT NULL,
	`reconsent_triggers` text DEFAULT '' NOT NULL,
	`history` text DEFAULT '[]' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `consent_records_project` ON `consent_records` (`project_id`);--> statement-breakpoint
CREATE TABLE `knowledge_holders` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`community_id` text NOT NULL,
	`name` text NOT NULL,
	`preferred_identifier` text DEFAULT '' NOT NULL,
	`anonymous_publicly` integer DEFAULT true NOT NULL,
	`role` text DEFAULT '' NOT NULL,
	`relationship_to_knowledge` text DEFAULT '' NOT NULL,
	`authority_scope` text DEFAULT '' NOT NULL,
	`attribution_preference` text DEFAULT '' NOT NULL,
	`contact_permissions` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `knowledge_permissions` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`record_id` text NOT NULL,
	`activity` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`conditions` text DEFAULT '' NOT NULL,
	`approving_authority_id` text,
	`approval_date` text,
	`expiry_date` text,
	`reconfirmation_required` integer DEFAULT false NOT NULL,
	`withdrawal_allowed` integer DEFAULT true NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `knowledge_permissions_activity` ON `knowledge_permissions` (`record_id`,`activity`);--> statement-breakpoint
CREATE TABLE `knowledge_records` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text,
	`community_id` text,
	`holder_id` text,
	`authority_id` text,
	`custodian_id` text,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`knowledge_type` text DEFAULT 'tek' NOT NULL,
	`description_public` text DEFAULT '' NOT NULL,
	`protected_content_ref` text,
	`source_type` text DEFAULT '' NOT NULL,
	`original_language` text DEFAULT '' NOT NULL,
	`collection_method` text DEFAULT '' NOT NULL,
	`collection_date` text,
	`access_status` text DEFAULT 'restricted' NOT NULL,
	`governance_status` text DEFAULT 'unknown' NOT NULL,
	`consent_status` text DEFAULT 'not_started' NOT NULL,
	`spatial_sensitivity` text DEFAULT 'hide' NOT NULL,
	`generalized_area` text DEFAULT '' NOT NULL,
	`publication_status` text DEFAULT 'unpublished' NOT NULL,
	`withdrawn` integer DEFAULT false NOT NULL,
	`provenance_complete` integer DEFAULT false NOT NULL,
	`local_contexts` text DEFAULT '{}' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `knowledge_records_project` ON `knowledge_records` (`project_id`);--> statement-breakpoint
CREATE INDEX `knowledge_records_community` ON `knowledge_records` (`community_id`);--> statement-breakpoint
CREATE TABLE `knowledge_uses` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`record_id` text NOT NULL,
	`activity` text NOT NULL,
	`output_type` text NOT NULL,
	`output_ref` text DEFAULT '' NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`used_by` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`flagged_reason` text,
	`used_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `knowledge_uses_record` ON `knowledge_uses` (`record_id`);--> statement-breakpoint
CREATE TABLE `participation_structures` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`community_id` text NOT NULL,
	`scenario` text DEFAULT 'Base' NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`status` text DEFAULT 'concept' NOT NULL,
	`basis` text DEFAULT '' NOT NULL,
	`rationale` text DEFAULT '' NOT NULL,
	`legal_structure` text DEFAULT '' NOT NULL,
	`project_company` text DEFAULT '' NOT NULL,
	`terms` text DEFAULT '{}' NOT NULL,
	`inflation_indexed` integer DEFAULT false NOT NULL,
	`transferability` text DEFAULT '' NOT NULL,
	`change_of_control` text DEFAULT '' NOT NULL,
	`termination` text DEFAULT '' NOT NULL,
	`approvals` text DEFAULT '{}' NOT NULL,
	`agreement_id` text,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `participation_structures_project` ON `participation_structures` (`project_id`,`scenario`);--> statement-breakpoint
ALTER TABLE `capital_profiles` ADD `community_alignment` text DEFAULT '{"flags":[],"preference":"unknown","supported":[],"source":""}' NOT NULL;