CREATE TABLE `grid_connections` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`operator` text DEFAULT '' NOT NULL,
	`poi` text DEFAULT '' NOT NULL,
	`voltage_kv` real,
	`queue_id` text DEFAULT '' NOT NULL,
	`application_date` text,
	`study_stage` text DEFAULT 'none' NOT NULL,
	`requested_mw` real,
	`approved_mw` real,
	`direction` text DEFAULT 'injection' NOT NULL,
	`network_upgrades` text DEFAULT '' NOT NULL,
	`upgrade_cost` real,
	`cost_allocation` text DEFAULT '' NOT NULL,
	`security_deposit` real,
	`currency` text DEFAULT 'USD' NOT NULL,
	`curtailment_risk` text DEFAULT '' NOT NULL,
	`transmission_constraints` text DEFAULT '' NOT NULL,
	`target_energization` text,
	`dependencies` text DEFAULT '' NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text
);
--> statement-breakpoint
CREATE INDEX `grid_connections_project` ON `grid_connections` (`project_id`);--> statement-breakpoint
CREATE TABLE `large_loads` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`name` text NOT NULL,
	`org_id` text,
	`project_id` text,
	`type` text NOT NULL,
	`stage` text DEFAULT 'prospect' NOT NULL,
	`country` text,
	`region` text DEFAULT '' NOT NULL,
	`lat` real,
	`lng` real,
	`mw` real,
	`mwh_year` real,
	`load_factor_pct` real,
	`redundancy` text DEFAULT 'unknown' NOT NULL,
	`uptime_pct` real,
	`renewable_target_pct` real,
	`carbon_target` text DEFAULT '' NOT NULL,
	`energization_date` text,
	`procurement` text DEFAULT '[]' NOT NULL,
	`ramp` text DEFAULT '' NOT NULL,
	`water_needs` text DEFAULT '' NOT NULL,
	`source` text DEFAULT '' NOT NULL,
	`source_url` text,
	`confidence` text DEFAULT 'unknown' NOT NULL,
	`as_of` text,
	`is_demo` text DEFAULT 'no' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text
);
--> statement-breakpoint
CREATE INDEX `large_loads_mandate` ON `large_loads` (`mandate_id`,`type`);--> statement-breakpoint
CREATE TABLE `ppas` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`revenue_stream_id` text,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`status` text DEFAULT 'prospect' NOT NULL,
	`buyer_org_id` text,
	`buyer_name` text DEFAULT '' NOT NULL,
	`guarantor_name` text DEFAULT '' NOT NULL,
	`generator_entity` text DEFAULT '' NOT NULL,
	`contracted_mw` real,
	`contracted_mwh_year` real,
	`start_date` text,
	`term_years` real,
	`price` real,
	`price_unit` text DEFAULT 'MWh' NOT NULL,
	`escalation_pct` real,
	`indexation` text DEFAULT '' NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`delivery_node` text DEFAULT '' NOT NULL,
	`settlement_node` text DEFAULT '' NOT NULL,
	`profile` text DEFAULT 'unknown' NOT NULL,
	`volume_commitment` text DEFAULT '' NOT NULL,
	`risk_allocation` text DEFAULT '{}' NOT NULL,
	`credit` text DEFAULT '{}' NOT NULL,
	`lender_rights` text DEFAULT '{}' NOT NULL,
	`conditions` text DEFAULT '[]' NOT NULL,
	`contract_id` text,
	`signed_date` text,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text
);
--> statement-breakpoint
CREATE INDEX `ppas_project` ON `ppas` (`project_id`);--> statement-breakpoint
CREATE TABLE `storage_specs` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`name` text DEFAULT 'Storage' NOT NULL,
	`chemistry` text DEFAULT 'lfp' NOT NULL,
	`power_mw` real NOT NULL,
	`energy_mwh` real NOT NULL,
	`cycles_per_year` real,
	`round_trip_pct` real,
	`degradation_pct_year` real,
	`useful_life_years` real,
	`augmentation` text DEFAULT '[]' NOT NULL,
	`warranty_years` real,
	`thermal_management` text DEFAULT '' NOT NULL,
	`fire_suppression` text DEFAULT '' NOT NULL,
	`ems` text DEFAULT '' NOT NULL,
	`pcs` text DEFAULT '' NOT NULL,
	`capex_per_kwh` real,
	`capex_per_kw` real,
	`fixed_om_per_kw_year` real,
	`charging_cost_per_mwh` real,
	`currency` text DEFAULT 'USD' NOT NULL,
	`services` text DEFAULT '[]' NOT NULL,
	`cost_source` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text
);
--> statement-breakpoint
CREATE INDEX `storage_specs_project` ON `storage_specs` (`project_id`);