CREATE TABLE `be_company_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`org_id` text NOT NULL,
	`legal_name` text,
	`company_status` text DEFAULT 'active' NOT NULL,
	`operating_regions` text DEFAULT '[]' NOT NULL,
	`taxonomy` text DEFAULT '[]' NOT NULL,
	`subsectors` text DEFAULT '[]' NOT NULL,
	`technology_type` text DEFAULT '' NOT NULL,
	`product_category` text DEFAULT '' NOT NULL,
	`building_segments` text DEFAULT '[]' NOT NULL,
	`stage_fit` text DEFAULT '[]' NOT NULL,
	`problem_solved` text DEFAULT '' NOT NULL,
	`summary` text DEFAULT '' NOT NULL,
	`maturity` text DEFAULT 'pilot' NOT NULL,
	`trl` integer,
	`crl` integer,
	`patents` text DEFAULT '' NOT NULL,
	`certifications` text DEFAULT '[]' NOT NULL,
	`standards` text DEFAULT '[]' NOT NULL,
	`constraints` text DEFAULT '' NOT NULL,
	`embodied_carbon_impact` text DEFAULT 'unknown' NOT NULL,
	`operational_carbon_impact` text DEFAULT 'unknown' NOT NULL,
	`water_impact` text DEFAULT 'unknown' NOT NULL,
	`waste_impact` text DEFAULT 'unknown' NOT NULL,
	`pricing_model` text DEFAULT '' NOT NULL,
	`cost_effect` text DEFAULT 'unknown' NOT NULL,
	`minimum_order` text DEFAULT '' NOT NULL,
	`production_capacity` text DEFAULT '' NOT NULL,
	`lead_time` text DEFAULT '' NOT NULL,
	`delivery_model` text DEFAULT '' NOT NULL,
	`geography_served` text DEFAULT '[]' NOT NULL,
	`funding_stage` text,
	`capital_raised` real,
	`capital_currency` text DEFAULT 'USD' NOT NULL,
	`latest_round` text DEFAULT '' NOT NULL,
	`investor_org_ids` text DEFAULT '[]' NOT NULL,
	`investor_names` text DEFAULT '[]' NOT NULL,
	`expansion_status` text DEFAULT '' NOT NULL,
	`target_customers` text DEFAULT '' NOT NULL,
	`target_regions` text DEFAULT '[]' NOT NULL,
	`partnership_interest` integer DEFAULT false NOT NULL,
	`distributor_interest` integer DEFAULT false NOT NULL,
	`pilot_interest` integer DEFAULT false NOT NULL,
	`relationship_status` text DEFAULT 'none' NOT NULL,
	`relationship_owner` text,
	`engagement_stage` text DEFAULT '' NOT NULL,
	`procurement_fit` text DEFAULT '' NOT NULL,
	`capital_fit` text DEFAULT '' NOT NULL,
	`advisory_fit` text DEFAULT '' NOT NULL,
	`market_entry_fit` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`next_action` text,
	`next_action_date` text,
	`recent_signals` text DEFAULT '[]' NOT NULL,
	`origin` text DEFAULT 'user_entered' NOT NULL,
	`source_url` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `be_company_profiles_org` ON `be_company_profiles` (`mandate_id`,`org_id`);--> statement-breakpoint
CREATE TABLE `be_knowledge` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`title` text NOT NULL,
	`knowledge_type` text NOT NULL,
	`summary` text DEFAULT '' NOT NULL,
	`knowledge_holder` text,
	`community` text,
	`custodian` text,
	`community_id` text,
	`geographic_context` text DEFAULT '' NOT NULL,
	`cultural_context` text DEFAULT '' NOT NULL,
	`access` text DEFAULT 'community_governed' NOT NULL,
	`consent_status` text DEFAULT 'not_requested' NOT NULL,
	`authorized_use` text DEFAULT '' NOT NULL,
	`commercial_use` integer DEFAULT false NOT NULL,
	`publication` integer DEFAULT false NOT NULL,
	`digitization` integer DEFAULT false NOT NULL,
	`attribution` text DEFAULT '' NOT NULL,
	`benefit_sharing_required` integer DEFAULT true NOT NULL,
	`benefit_sharing` text DEFAULT '' NOT NULL,
	`equity_participation` text DEFAULT '' NOT NULL,
	`revenue_share` text DEFAULT '' NOT NULL,
	`community_fund` text DEFAULT '' NOT NULL,
	`community_governance` text DEFAULT '' NOT NULL,
	`restrictions` text DEFAULT '' NOT NULL,
	`review_date` text,
	`source` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `be_matches` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`project_id` text NOT NULL,
	`subject_type` text NOT NULL,
	`subject_id` text,
	`category` text NOT NULL,
	`label` text NOT NULL,
	`reason` text NOT NULL,
	`confidence` text DEFAULT 'moderate' NOT NULL,
	`impacts` text DEFAULT '{}' NOT NULL,
	`stage_fit` text DEFAULT '' NOT NULL,
	`provider_org_ids` text DEFAULT '[]' NOT NULL,
	`rank` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'suggested' NOT NULL,
	`run_at` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `be_matches_project` ON `be_matches` (`project_id`,`category`);--> statement-breakpoint
CREATE TABLE `be_materials` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`name` text NOT NULL,
	`family` text NOT NULL,
	`supplier_org_id` text,
	`origin` text DEFAULT 'user_entered' NOT NULL,
	`origin_place` text DEFAULT '' NOT NULL,
	`local_availability` text DEFAULT '[]' NOT NULL,
	`manufacturing_location` text DEFAULT '' NOT NULL,
	`embodied_carbon` real,
	`embodied_carbon_unit` text DEFAULT 'kgCO2e/m3' NOT NULL,
	`embodied_carbon_state` text DEFAULT 'unverified' NOT NULL,
	`epd_id` text,
	`recycled_content_pct` real,
	`biobased_pct` real,
	`end_of_life` text DEFAULT '' NOT NULL,
	`recyclability` text DEFAULT 'unknown' NOT NULL,
	`reusability` text DEFAULT 'unknown' NOT NULL,
	`toxicity` text DEFAULT '' NOT NULL,
	`voc` text DEFAULT '' NOT NULL,
	`moisture` text DEFAULT '' NOT NULL,
	`thermal` text DEFAULT '' NOT NULL,
	`fire` text DEFAULT '' NOT NULL,
	`acoustic` text DEFAULT '' NOT NULL,
	`structural` text DEFAULT '' NOT NULL,
	`durability` text DEFAULT '' NOT NULL,
	`maintenance` text DEFAULT '' NOT NULL,
	`climates` text DEFAULT '[]' NOT NULL,
	`hazards` text DEFAULT '[]' NOT NULL,
	`tags` text DEFAULT '[]' NOT NULL,
	`certifications` text DEFAULT '[]' NOT NULL,
	`cost` text DEFAULT '' NOT NULL,
	`lead_time` text DEFAULT '' NOT NULL,
	`supplier_capacity` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `be_materials_family` ON `be_materials` (`mandate_id`,`family`);--> statement-breakpoint
CREATE TABLE `be_opportunities` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`org_id` text NOT NULL,
	`title` text NOT NULL,
	`kinds` text DEFAULT '[]' NOT NULL,
	`project_ids` text DEFAULT '[]' NOT NULL,
	`regenera_assets` text DEFAULT '' NOT NULL,
	`fee_models` text DEFAULT '[]' NOT NULL,
	`fee_compliance` text DEFAULT 'unknown' NOT NULL,
	`status` text DEFAULT 'identified' NOT NULL,
	`deal_id` text,
	`signal_id` text,
	`owner` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `be_opportunities_org` ON `be_opportunities` (`org_id`);--> statement-breakpoint
CREATE TABLE `be_signals` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`date` text NOT NULL,
	`org_id` text,
	`entity` text NOT NULL,
	`type` text NOT NULL,
	`summary` text NOT NULL,
	`source` text NOT NULL,
	`source_url` text,
	`region` text,
	`importance` text DEFAULT 'medium' NOT NULL,
	`why` text DEFAULT '' NOT NULL,
	`relevance` text DEFAULT '' NOT NULL,
	`project_ids` text DEFAULT '[]' NOT NULL,
	`investor_org_ids` text DEFAULT '[]' NOT NULL,
	`suggested_action` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`origin` text DEFAULT 'user_entered' NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `be_signals_date` ON `be_signals` (`mandate_id`,`date`);--> statement-breakpoint
CREATE TABLE `be_systems` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`name` text NOT NULL,
	`kind` text NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`provider_org_ids` text DEFAULT '[]' NOT NULL,
	`climates` text DEFAULT '[]' NOT NULL,
	`hazards` text DEFAULT '[]' NOT NULL,
	`building_types` text DEFAULT '[]' NOT NULL,
	`speed_effect` text DEFAULT 'unknown' NOT NULL,
	`cost_effect` text DEFAULT 'unknown' NOT NULL,
	`carbon_effect` text DEFAULT 'unknown' NOT NULL,
	`labor_effect` text DEFAULT 'unknown' NOT NULL,
	`modular_feasibility` text DEFAULT '' NOT NULL,
	`risks` text DEFAULT '' NOT NULL,
	`origin` text DEFAULT 'user_entered' NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `be_technologies` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`org_id` text,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`subcategory` text DEFAULT '' NOT NULL,
	`trl` integer,
	`crl` integer,
	`maturity` text DEFAULT 'pilot' NOT NULL,
	`deployment_count` integer,
	`deployment_locations` text DEFAULT '[]' NOT NULL,
	`climates` text DEFAULT '[]' NOT NULL,
	`hazards` text DEFAULT '[]' NOT NULL,
	`building_types` text DEFAULT '[]' NOT NULL,
	`project_sizes` text DEFAULT '[]' NOT NULL,
	`effects` text DEFAULT '{}' NOT NULL,
	`permitting` text DEFAULT 'unknown' NOT NULL,
	`installation` text DEFAULT 'unknown' NOT NULL,
	`maintenance` text DEFAULT 'unknown' NOT NULL,
	`bankability` text DEFAULT 'unknown' NOT NULL,
	`insurability` text DEFAULT 'unknown' NOT NULL,
	`warranty` text DEFAULT '' NOT NULL,
	`certifications` text DEFAULT '[]' NOT NULL,
	`technical_dependencies` text DEFAULT '' NOT NULL,
	`supply_chain_dependencies` text DEFAULT '' NOT NULL,
	`deployment_risks` text DEFAULT '' NOT NULL,
	`case_studies` text DEFAULT '' NOT NULL,
	`references` text DEFAULT '' NOT NULL,
	`stage_fit` text DEFAULT '[]' NOT NULL,
	`origin` text DEFAULT 'user_entered' NOT NULL,
	`source_url` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `be_technologies_category` ON `be_technologies` (`mandate_id`,`category`);--> statement-breakpoint
CREATE INDEX `be_technologies_org` ON `be_technologies` (`org_id`);--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `approved_status` text DEFAULT 'not_assessed' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `technical_qualification` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `financial_qualification` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `certifications` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `delivery_time` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `payment_terms` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `pricing_note` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `network_profiles` ADD `procurement_contact_id` text;