CREATE TABLE `approvals` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`kind` text NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`commercial_mandate_id` text,
	`title` text NOT NULL,
	`detail` text DEFAULT '' NOT NULL,
	`requester` text NOT NULL,
	`approver` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`rationale` text DEFAULT '' NOT NULL,
	`conditions` text DEFAULT '' NOT NULL,
	`document_version` text,
	`comments` text DEFAULT '[]' NOT NULL,
	`decided_by` text,
	`decided_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `approvals_pending` ON `approvals` (`mandate_id`,`status`);--> statement-breakpoint
CREATE INDEX `approvals_entity` ON `approvals` (`entity_type`,`entity_id`);--> statement-breakpoint
CREATE TABLE `commercial_mandates` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`desk` text NOT NULL,
	`client_org_id` text,
	`client_name` text DEFAULT '' NOT NULL,
	`client_entity` text DEFAULT '' NOT NULL,
	`engagement_id` text,
	`owner` text,
	`lead` text,
	`originator` text,
	`sector` text DEFAULT '' NOT NULL,
	`subsector` text DEFAULT '' NOT NULL,
	`asset_class` text DEFAULT '' NOT NULL,
	`technologies` text DEFAULT '[]' NOT NULL,
	`geography` text DEFAULT '{}' NOT NULL,
	`criteria` text DEFAULT '{}' NOT NULL,
	`exclusions` text DEFAULT '' NOT NULL,
	`qualification_note` text DEFAULT '' NOT NULL,
	`legal_restrictions` text DEFAULT '' NOT NULL,
	`compliance_requirements` text DEFAULT '' NOT NULL,
	`confidentiality` text DEFAULT 'confidential' NOT NULL,
	`outreach_permission` text DEFAULT 'approval_each' NOT NULL,
	`data_access` text DEFAULT 'named_team' NOT NULL,
	`success_definition` text DEFAULT '' NOT NULL,
	`delivery_floor` text DEFAULT '[]' NOT NULL,
	`reporting_cadence` text DEFAULT 'weekly' NOT NULL,
	`engagement_model` text,
	`breadth` text DEFAULT 'regional' NOT NULL,
	`term_months` real,
	`retainer` real DEFAULT 0 NOT NULL,
	`pilot_fee` real DEFAULT 0 NOT NULL,
	`implementation_fee` real DEFAULT 0 NOT NULL,
	`data_cost` real DEFAULT 0 NOT NULL,
	`partner_cost` real DEFAULT 0 NOT NULL,
	`travel_cost` real DEFAULT 0 NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`success_economics` text DEFAULT '{}' NOT NULL,
	`attribution_rules` text DEFAULT '' NOT NULL,
	`contract_id` text,
	`start_date` text,
	`review_date` text,
	`end_date` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`health` text DEFAULT 'not_started' NOT NULL,
	`health_note` text DEFAULT '' NOT NULL,
	`confidence` text DEFAULT 'medium' NOT NULL,
	`priority` text DEFAULT 'medium' NOT NULL,
	`next_action` text DEFAULT '' NOT NULL,
	`next_action_date` text,
	`public_label` text DEFAULT '' NOT NULL,
	`publish_approved` integer DEFAULT false NOT NULL,
	`sources` text DEFAULT '[]' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `commercial_mandates_ws` ON `commercial_mandates` (`mandate_id`,`status`);--> statement-breakpoint
CREATE INDEX `commercial_mandates_type` ON `commercial_mandates` (`type`);--> statement-breakpoint
CREATE TABLE `mandate_candidates` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`commercial_mandate_id` text NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`name` text NOT NULL,
	`account_org_id` text,
	`project_id` text,
	`stage` text DEFAULT 'discovered' NOT NULL,
	`fit` text DEFAULT '{}' NOT NULL,
	`checks` text DEFAULT '{}' NOT NULL,
	`met_count` integer DEFAULT 0 NOT NULL,
	`unknown_count` integer DEFAULT 0 NOT NULL,
	`fail_count` integer DEFAULT 0 NOT NULL,
	`completeness` real DEFAULT 0 NOT NULL,
	`priority` text DEFAULT 'medium' NOT NULL,
	`data` text DEFAULT '{}' NOT NULL,
	`evidence` text DEFAULT '[]' NOT NULL,
	`est_value` real,
	`est_value_basis` text DEFAULT '' NOT NULL,
	`window_start` text,
	`window_end` text,
	`window_basis` text DEFAULT '' NOT NULL,
	`attribution` text DEFAULT 'unattributed' NOT NULL,
	`origin_date` text,
	`originator` text,
	`source` text DEFAULT '' NOT NULL,
	`pre_existing` integer DEFAULT false NOT NULL,
	`client_response` text,
	`client_response_by` text,
	`client_response_at` text,
	`client_response_note` text DEFAULT '' NOT NULL,
	`dispute_status` text DEFAULT 'none' NOT NULL,
	`next_action` text DEFAULT '' NOT NULL,
	`owner` text,
	`pursuit_id` text,
	`feedback` text,
	`feedback_note` text DEFAULT '' NOT NULL,
	`stage_history` text DEFAULT '[]' NOT NULL,
	`first_seen_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`last_signal_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`commercial_mandate_id`) REFERENCES `commercial_mandates`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `mandate_candidates_entity` ON `mandate_candidates` (`commercial_mandate_id`,`entity_type`,`entity_id`);--> statement-breakpoint
CREATE INDEX `mandate_candidates_stage` ON `mandate_candidates` (`commercial_mandate_id`,`stage`);--> statement-breakpoint
CREATE TABLE `mandate_deliveries` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`commercial_mandate_id` text NOT NULL,
	`period` text NOT NULL,
	`metrics` text DEFAULT '{}' NOT NULL,
	`quality` text DEFAULT '' NOT NULL,
	`shortfall` text DEFAULT '' NOT NULL,
	`remediation` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`commercial_mandate_id`) REFERENCES `commercial_mandates`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `mandate_deliveries_period` ON `mandate_deliveries` (`commercial_mandate_id`,`period`);--> statement-breakpoint
CREATE TABLE `mandate_signals` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`commercial_mandate_id` text NOT NULL,
	`candidate_id` text,
	`kind` text NOT NULL,
	`what_changed` text NOT NULL,
	`why_it_matters` text DEFAULT '' NOT NULL,
	`recommended_action` text DEFAULT '' NOT NULL,
	`urgency` text DEFAULT 'normal' NOT NULL,
	`confidence` text DEFAULT 'medium' NOT NULL,
	`inference` integer DEFAULT false NOT NULL,
	`source` text NOT NULL,
	`source_url` text,
	`observed_at` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`dedupe_key` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `mandate_signals_dedupe` ON `mandate_signals` (`commercial_mandate_id`,`dedupe_key`);--> statement-breakpoint
CREATE INDEX `mandate_signals_new` ON `mandate_signals` (`mandate_id`,`status`);--> statement-breakpoint
CREATE TABLE `pursuits` (
	`id` text PRIMARY KEY NOT NULL,
	`mandate_id` text NOT NULL,
	`commercial_mandate_id` text,
	`candidate_id` text,
	`type` text NOT NULL,
	`name` text NOT NULL,
	`account_org_id` text,
	`project_id` text,
	`counterparty` text DEFAULT '' NOT NULL,
	`owner` text,
	`team` text DEFAULT '[]' NOT NULL,
	`value` real,
	`currency` text DEFAULT 'USD' NOT NULL,
	`value_basis` text DEFAULT '' NOT NULL,
	`stage` text NOT NULL,
	`probability_override` real,
	`probability_why` text DEFAULT '' NOT NULL,
	`probability_at` text,
	`expected_outcome` text DEFAULT '' NOT NULL,
	`expected_date` text,
	`next_action` text DEFAULT '' NOT NULL,
	`next_action_date` text,
	`last_action_at` text,
	`relationship_status` text DEFAULT 'none' NOT NULL,
	`risks` text DEFAULT '[]' NOT NULL,
	`competitors` text DEFAULT '[]' NOT NULL,
	`decision_makers` text DEFAULT '[]' NOT NULL,
	`commercial_structure` text DEFAULT '' NOT NULL,
	`diligence_status` text DEFAULT 'not_started' NOT NULL,
	`document_status` text DEFAULT 'not_started' NOT NULL,
	`attribution` text DEFAULT 'unattributed' NOT NULL,
	`bid_criteria` text DEFAULT '{}' NOT NULL,
	`bid_decision` text,
	`bid_rationale` text DEFAULT '' NOT NULL,
	`bid_decided_by` text,
	`bid_decided_at` text,
	`deal_id` text,
	`outcome` text DEFAULT 'open' NOT NULL,
	`win_loss` text DEFAULT '{}' NOT NULL,
	`stage_history` text DEFAULT '[]' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `pursuits_ws` ON `pursuits` (`mandate_id`,`outcome`);--> statement-breakpoint
CREATE INDEX `pursuits_mandate` ON `pursuits` (`commercial_mandate_id`);--> statement-breakpoint
CREATE TABLE `queue_projects` (
	`key` text PRIMARY KEY NOT NULL,
	`iso` text NOT NULL,
	`number` text NOT NULL,
	`state` text DEFAULT '' NOT NULL,
	`county` text DEFAULT '' NOT NULL,
	`poi` text DEFAULT '' NOT NULL,
	`transmission_owner` text DEFAULT '' NOT NULL,
	`fuel` text DEFAULT '' NOT NULL,
	`technology` text DEFAULT '' NOT NULL,
	`mw` real,
	`mw_winter` real,
	`queue_date` text,
	`in_service_date` text,
	`withdrawn_date` text,
	`status` text DEFAULT '' NOT NULL,
	`study_phase` text DEFAULT '' NOT NULL,
	`ia_status` text DEFAULT '' NOT NULL,
	`raw` text DEFAULT '{}' NOT NULL,
	`first_seen_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`last_seen_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`last_changed_at` text,
	`changes` text DEFAULT '[]' NOT NULL
);
--> statement-breakpoint
CREATE INDEX `queue_projects_iso` ON `queue_projects` (`iso`,`technology`,`status`);--> statement-breakpoint
CREATE INDEX `queue_projects_state` ON `queue_projects` (`state`);