// Seed service catalogue. Price bands are Regenera's INTERNAL DEFAULTS from the commercial specification (editable
// per service), not market facts. Every service states Regenera's role and where a specialist of record is required.
import type { BILLING_TYPES, DEPTHS, LIFECYCLE_PHASES, REGENERA_ROLES, SERVICE_FAMILIES } from "./vocab";

export type ServiceSeed = {
  key: string; family: keyof typeof SERVICE_FAMILIES; name: string; depth: keyof typeof DEPTHS; description: string; idealClient: string; stages: string[];
  inputs: string[]; deliverables: string[]; timelineWeeks: number; billingType: keyof typeof BILLING_TYPES; bandLow: number; bandHigh: number | null; perMonth: boolean;
  expectedHours: number; targetMarginPct: number; role: keyof typeof REGENERA_ROLES; specialistRequired: string[]; workflow: string[]; phase: keyof typeof LIFECYCLE_PHASES;
  next: string[]; approvalRequired: boolean; legalNotes: string; portalAccess: "none" | "deliverables" | "full"; listPrice?: number;
};

const S = (s: Partial<ServiceSeed> & Pick<ServiceSeed, "key" | "family" | "name" | "bandLow">): ServiceSeed => ({
  depth: "standard", description: "", idealClient: "", stages: [], inputs: [], deliverables: [], timelineWeeks: 4, billingType: "fixed", bandHigh: null, perMonth: false,
  expectedHours: 0, targetMarginPct: 55, role: "advisory", specialistRequired: [], workflow: ["Kickoff", "Data intake", "Analysis", "Internal review", "Client review", "Final delivery"],
  phase: "p1", next: [], approvalRequired: false, legalNotes: "", portalAccess: "deliverables", ...s,
});

export const SERVICE_SEEDS: ServiceSeed[] = [
  S({ key: "diagnostic", family: "strategy", name: "Initial diagnostic", bandLow: 0, bandHigh: 2_500, phase: "p0", timelineWeeks: 1, expectedHours: 6, description: "Qualification and introductory assessment; very limited scope.", deliverables: ["Diagnostic note"], next: ["project_screening", "site_intel_screen"], workflow: ["Intake call", "Desk review", "Diagnostic note"] }),
  S({ key: "project_screening", family: "strategy", name: "Project / site screening", bandLow: 5_000, bandHigh: 15_000, phase: "p1", timelineWeeks: 2, expectedHours: 30, deliverables: ["Screening memo", "Initial risk list"], inputs: ["Project description", "Location", "Stage"], next: ["system_fit", "prefeasibility"] }),
  S({ key: "site_intel_screen", family: "spatial", name: "Site intelligence", depth: "screen", bandLow: 5_000, bandHigh: 15_000, phase: "p1", timelineWeeks: 2, expectedHours: 25, description: "Desktop review from public data: initial risks and an initial System Fit read.", inputs: ["Boundary or coordinates"], deliverables: ["Site screening brief"], next: ["site_intel_assess"] }),
  S({ key: "site_intel_assess", family: "spatial", name: "Site intelligence", depth: "assess", bandLow: 10_000, bandHigh: 30_000, phase: "p1", timelineWeeks: 4, expectedHours: 70, description: "Full ATLAS workbench: constraints, terrain, hydrology, infrastructure, environmental analysis and a site report.", inputs: ["Boundary", "Parcel data", "Known constraints", "Existing studies"], deliverables: ["Site report", "ATLAS map pack", "Development envelope", "Required studies list"], specialistRequired: ["Topographic survey", "Hydrological study where flagged"], next: ["site_intel_execute", "prefeasibility", "financial_model"] }),
  S({ key: "site_intel_execute", family: "spatial", name: "Site intelligence", depth: "execute", bandLow: 20_000, bandHigh: 60_000, phase: "p2", timelineWeeks: 8, expectedHours: 120, role: "coordination", description: "Specialist coordination, field studies, engineering handoff, development envelope and ongoing support.", deliverables: ["Engineering handoff package", "Field verification", "Updated site intelligence"], specialistRequired: ["Topographic survey", "Geotechnical survey", "Wetland delineation", "Engineering stamp"], next: ["development_management"] }),
  S({ key: "system_fit", family: "spatial", name: "System Fit assessment", bandLow: 10_000, bandHigh: 30_000, phase: "p1", timelineWeeks: 3, expectedHours: 60, deliverables: ["System Fit report", "Alternatives and hybrid options"], next: ["prefeasibility", "eva"] }),
  S({ key: "prefeasibility", family: "development", name: "Full pre-feasibility", bandLow: 20_000, bandHigh: 75_000, phase: "p2", timelineWeeks: 8, expectedHours: 160, role: "coordination", deliverables: ["Pre-feasibility report", "Preliminary financial model", "Permit matrix", "Development plan"], specialistRequired: ["Engineering stamp where design is required", "Environmental assessment"], next: ["financial_model", "development_management", "capital_strategy"] }),
  S({ key: "development_gap", family: "development", name: "Development gap analysis", bandLow: 7_500, bandHigh: 20_000, phase: "p2", timelineWeeks: 3, expectedHours: 40, deliverables: ["Gap analysis", "Development plan"], next: ["development_management"] }),
  S({ key: "development_management", family: "development", name: "Development management", billingType: "development_management", bandLow: 7_500, bandHigh: 25_000, perMonth: true, phase: "p3", timelineWeeks: 26, expectedHours: 60, role: "project_management", deliverables: ["Monthly development report", "Workplan and schedule", "Risk register"], workflow: ["Mobilisation", "Monthly cycle", "Gate reviews"], next: ["investor_readiness", "capital_strategy"] }),
  S({ key: "owners_rep", family: "development", name: "Owner's representative support", billingType: "monthly_retainer", bandLow: 10_000, bandHigh: 30_000, perMonth: true, phase: "p3", role: "owners_rep", timelineWeeks: 26, expectedHours: 70, specialistRequired: ["Engineer of record"], legalNotes: "Scope must state Regenera acts as representative, not engineer of record." }),
  S({ key: "financial_model", family: "financial", name: "Financial model / underwriting", bandLow: 10_000, bandHigh: 40_000, phase: "p2", timelineWeeks: 4, expectedHours: 80, role: "analysis", inputs: ["Project description", "CAPEX", "OPEX", "Revenue contracts", "Schedule", "Financing terms", "Tax", "Engineering", "Land"], deliverables: ["Financial model", "Assumption register", "Sensitivity and stress analysis", "Model memo"], workflow: ["Kickoff", "Data intake", "Assumption review", "Model build", "Internal review", "Scenario analysis", "Client review", "Final model", "Final memo"], specialistRequired: ["Tax opinion where material", "Model audit for financial close"], next: ["capital_strategy", "investor_readiness"] }),
  S({ key: "capital_strategy", family: "capital", name: "Capital strategy", bandLow: 15_000, bandHigh: 50_000, phase: "p2", timelineWeeks: 6, expectedHours: 90, deliverables: ["Capital strategy", "Capital stack options", "Investor landscape"], legalNotes: "Strategy and mapping only; no regulated securities activity. Introductions only where permissible.", next: ["investor_readiness", "transaction_support"] }),
  S({ key: "eva", family: "environmental", name: "Environmental value assessment (EVA)", bandLow: 15_000, bandHigh: 50_000, phase: "p2", timelineWeeks: 6, expectedHours: 90, deliverables: ["EVA report", "Environmental market feasibility"], specialistRequired: ["Carbon / MRV specialist", "Biodiversity survey"], next: ["capital_strategy"] }),
  S({ key: "investor_readiness", family: "capital", name: "Investor readiness / data room", bandLow: 15_000, bandHigh: 40_000, phase: "p4", timelineWeeks: 6, expectedHours: 80, deliverables: ["Data room", "Investor brief", "Investment memo"], next: ["transaction_support"] }),
  S({ key: "transaction_support", family: "transaction", name: "Capital / transaction support", billingType: "transaction_support", bandLow: 10_000, bandHigh: 30_000, perMonth: true, phase: "p4", timelineWeeks: 16, expectedHours: 70, approvalRequired: true, legalNotes: "Performance-linked compensation and capital introduction require counsel review and internal approval.", specialistRequired: ["Legal counsel", "Licensed intermediary where securities are offered"], next: ["portfolio_monitoring"] }),
  S({ key: "fractional_office", family: "portfolio", name: "Fractional development office", billingType: "monthly_retainer", bandLow: 15_000, bandHigh: 40_000, perMonth: true, phase: "p3", timelineWeeks: 52, expectedHours: 90, role: "project_management" }),
  S({ key: "portfolio_advisory", family: "portfolio", name: "Portfolio / family office advisory", billingType: "monthly_retainer", bandLow: 15_000, bandHigh: 50_000, perMonth: true, phase: "p5", timelineWeeks: 52, expectedHours: 60 }),
  S({ key: "portfolio_monitoring", family: "portfolio", name: "Portfolio / project monitoring", billingType: "subscription", bandLow: 2_500, bandHigh: 10_000, perMonth: true, phase: "p5", timelineWeeks: 52, expectedHours: 12 }),
  S({ key: "major_mandate", family: "transaction", name: "Major project / multi-workstream mandate", billingType: "hybrid", bandLow: 50_000, bandHigh: 250_000, phase: "p3", timelineWeeks: 26, expectedHours: 400, approvalRequired: true }),
  S({ key: "jurisdiction_intel", family: "intelligence", name: "Jurisdiction intelligence", bandLow: 7_500, bandHigh: 25_000, phase: "p1", timelineWeeks: 3, expectedHours: 40, specialistRequired: ["Local counsel for legal conclusions"], legalNotes: "Research and issue spotting, not legal advice." }),
  S({ key: "nature_transition", family: "environmental", name: "Nature & capital transition strategy", bandLow: 25_000, bandHigh: 90_000, phase: "p2", timelineWeeks: 8, expectedHours: 150, role: "analysis", idealClient: "Family offices, landowners, developers, infrastructure companies, funds, corporations, municipalities, project sponsors", description: "Capital flow mapping, nature dependency and impact analysis, financial drivers and subsidy analysis, transition scenarios, capital reallocation, financing strategy and an implementation roadmap.", inputs: ["Portfolio or project list", "Land holdings / boundaries", "Financial data", "Existing ESG or environmental studies"], deliverables: ["Capital flow map", "Dependency and impact register", "Subsidy / incentive analysis", "Nature-adjusted scenarios", "Capital reallocation and financing strategy", "Implementation roadmap"], workflow: ["Kickoff", "Data intake", "Flow mapping", "Dependencies and impacts", "Drivers and incentives", "Transition scenarios", "Internal review", "Client review", "Roadmap"], specialistRequired: ["Ecologist / biodiversity specialist for field baselines", "Valuation specialist where impacts are monetised"], legalNotes: "Classifications are evidence-based analysis, not assurance or certification.", next: ["capital_strategy", "eva", "financial_model"] }),
  S({ key: "market_intel", family: "intelligence", name: "Market intelligence", bandLow: 7_500, bandHigh: 25_000, phase: "p1", timelineWeeks: 3, expectedHours: 40, deliverables: ["Market brief"], next: ["project_screening"] }),
  S({ key: "regulatory_monitoring", family: "intelligence", name: "Regulatory / strategic monitoring", billingType: "subscription", bandLow: 2_000, bandHigh: 8_000, perMonth: true, phase: "p5", timelineWeeks: 52, expectedHours: 10, legalNotes: "Research and issue spotting, not legal advice." }),
  S({ key: "diligence_coordination", family: "transaction", name: "Diligence coordination", bandLow: 15_000, bandHigh: 50_000, phase: "p4", timelineWeeks: 8, expectedHours: 100, role: "coordination", specialistRequired: ["Legal counsel", "Technical adviser", "Tax adviser"], deliverables: ["Diligence tracker", "Q&A log", "Issues list"], next: ["transaction_support"] }),
  S({ key: "permitting_coordination", family: "development", name: "Permitting coordination", billingType: "monthly_retainer", bandLow: 5_000, bandHigh: 15_000, perMonth: true, phase: "p3", timelineWeeks: 26, expectedHours: 40, role: "coordination", deliverables: ["Permit matrix", "Permit schedule", "Agency log"], specialistRequired: ["Local counsel", "Environmental consultant"] }),
  // Funding & capital strategy (phase 11). Public & blended finance advisory, not commodity grant writing. Internal
  // planning ranges, editable; fixed / milestone / retainer by default. Contingent fees need legal / program review.
  ...FUNDING_SERVICES(),
];

function FUNDING_SERVICES(): ServiceSeed[] {
  const legal = "Fixed, milestone or retainer fees. A contingent / success fee on public funding needs LEGAL / PROGRAM REVIEW: many grant and procurement rules restrict or prohibit it. Never promise an award.";
  return [
    S({ key: "funding_scan", family: "funding", name: "Funding scan / eligibility memo", bandLow: 2_500, bandHigh: 7_500, phase: "p0", timelineWeeks: 2, expectedHours: 18, targetMarginPct: 65, legalNotes: legal, description: "Which programs fit the client's projects and whether the client appears eligible, with sources.", deliverables: ["Funding scan", "Eligibility memo"], next: ["funding_diagnostic"] }),
    S({ key: "funding_diagnostic", family: "funding", name: "Funding readiness diagnostic", listPrice: 7_500, bandLow: 5_000, bandHigh: 15_000, phase: "p0", timelineWeeks: 3, expectedHours: 30, targetMarginPct: 65, legalNotes: legal, description: "Eligibility, opportunity analysis, project fit, applicant readiness, consortium and evidence gaps, co-finance, application workplan and a bid / no-bid recommendation.", idealClient: "A funding-first prospect or client with a live call", deliverables: ["Eligibility assessment", "Opportunity analysis", "Project fit", "Applicant readiness", "Consortium gap", "Evidence gap", "Co-finance requirement", "Application workplan", "Bid / no-bid recommendation", "Next-step strategy"], workflow: ["Intake", "Call interpretation", "Readiness assessment", "Gap analysis", "Internal review", "Client readout"], next: ["application_strategy", "full_application", "consortium_formation"] }),
    S({ key: "application_strategy", family: "funding", name: "Application strategy", bandLow: 10_000, bandHigh: 25_000, phase: "p2", timelineWeeks: 4, expectedHours: 60, targetMarginPct: 58, legalNotes: legal, deliverables: ["Application strategy", "Storyline and scoring map", "Workplan"], next: ["full_application"] }),
    S({ key: "full_application", family: "funding", name: "Full application / bid management", billingType: "milestone", bandLow: 20_000, bandHigh: 60_000, phase: "p2", timelineWeeks: 8, expectedHours: 110, targetMarginPct: 55, legalNotes: legal, role: "coordination", specialistRequired: ["Sector SME", "Budget / financial reviewer"], deliverables: ["Application package", "Budget and justification", "Compliance checklist", "Submission record"], workflow: ["Program interpretation", "Eligibility confirmation", "Workplan", "Narrative", "Budget", "Partners and letters", "Reviews", "Final QA", "Submission (client or authorized person)"], next: ["post_award_support", "capital_stack_advisory"] }),
    S({ key: "complex_application", family: "funding", name: "Complex consortium / infrastructure application", billingType: "milestone", bandLow: 50_000, bandHigh: 100_000, phase: "p2", timelineWeeks: 12, expectedHours: 260, targetMarginPct: 55, legalNotes: legal, role: "coordination", specialistRequired: ["Sector SME", "Financial modeler", "Legal counsel for consortium agreements"], deliverables: ["Application package", "Consortium agreement terms (for counsel)", "Budget model"], next: ["post_award_support"] }),
    S({ key: "consortium_formation", family: "funding", name: "Consortium formation", bandLow: 7_500, bandHigh: 25_000, phase: "p2", timelineWeeks: 4, expectedHours: 45, targetMarginPct: 58, legalNotes: legal, deliverables: ["Partner map", "Consortium gap analysis", "Commitment letters tracker"], next: ["full_application"] }),
    S({ key: "capital_stack_advisory", family: "funding", name: "Capital stack / co-finance advisory", bandLow: 15_000, bandHigh: 50_000, phase: "p4", timelineWeeks: 6, expectedHours: 90, targetMarginPct: 60, legalNotes: `${legal} Strategy and mapping only; no regulated securities activity.`, deliverables: ["Capital stack scenarios", "Co-finance plan", "Funding gap analysis"], next: ["capital_strategy"] }),
    S({ key: "funding_retainer", family: "funding", name: "Funding intelligence retainer", billingType: "monthly_retainer", bandLow: 3_000, bandHigh: 10_000, perMonth: true, phase: "p5", timelineWeeks: 52, expectedHours: 20, targetMarginPct: 62, legalNotes: legal, deliverables: ["Monthly funding brief", "Pipeline of relevant calls"] }),
    S({ key: "post_award_support", family: "funding", name: "Post-award program support", billingType: "monthly_retainer", bandLow: 5_000, bandHigh: 20_000, perMonth: true, phase: "p5", timelineWeeks: 52, expectedHours: 30, targetMarginPct: 58, legalNotes: legal, role: "project_management", deliverables: ["Reporting calendar", "Milestone and KPI tracking", "Expenditure and reimbursement log", "Compliance file"] }),
  ];
}

/** Scope builder: suggested workstreams for a project type and stage (the user edits the result). */
export function suggestWorkstreams(stage: string, objective: "screen" | "develop" | "finance" | "monitor"): string[] {
  const s = stage.toLowerCase();
  if (objective === "monitor") return ["portfolio_monitoring"];
  if (/opportunity|screening|diagnostic/.test(s)) return objective === "finance" ? ["project_screening", "financial_model", "capital_strategy"] : ["site_intel_assess", "system_fit", "jurisdiction_intel", "development_gap"];
  if (/readiness|development|structuring/.test(s)) return objective === "finance" ? ["financial_model", "capital_strategy", "investor_readiness"] : ["prefeasibility", "development_gap", "development_management"];
  if (/capital|diligence|financial_close/.test(s)) return ["investor_readiness", "transaction_support", "financial_model"];
  return ["project_screening", "site_intel_screen"];
}
