// The institutional data catalogue (docs/data/WRI.md). Providers and datasets are code-defined so every environment
// has the same provenance; the database mirrors them (data_providers, datasets) and adds live state (sync jobs,
// health). Licence fields are as understood when written; `null` means "verify before commercial use or export".
// Adding a dataset: add a row here; add an adapter under lib/data-providers/<provider>/ only when there is a real API.
import type { DataProvider, RegeneraDataset } from "./types";

export const PROVIDERS: DataProvider[] = [
  {
    key: "wri", name: "World Resources Institute", tagline: "Open environmental and development intelligence", tier: 1, kind: "institutional", url: "https://www.wri.org/data",
    platforms: [
      { key: "aqueduct", name: "Aqueduct", url: "https://www.wri.org/aqueduct", note: "Water risk: stress, depletion, variability, drought and flood, current and future scenarios." },
      { key: "gfw", name: "Global Forest Watch", url: "https://www.globalforestwatch.org", note: "Tree cover, loss, primary forest, carbon, concessions and alerts. Data API needs a free key." },
      { key: "resource_watch", name: "Resource Watch", url: "https://resourcewatch.org", note: "Curated catalogue across climate, water, energy, society and economy. Public metadata API." },
      { key: "eae", name: "Energy Access Explorer", url: "https://www.energyaccessexplorer.org", note: "Demand and supply-side energy access: population, social infrastructure, productive uses, grid." },
      { key: "lcl", name: "Land & Carbon Lab", url: "https://landcarbonlab.org", note: "Land conversion, carbon stocks and removals, restoration and landscape condition." },
      { key: "wri_explorer", name: "WRI Data Explorer", url: "https://datasets.wri.org", note: "Index of WRI datasets with licences and methods." },
    ],
  },
  { key: "world_bank", name: "World Bank", tagline: "Development indicators and procurement", tier: 1, kind: "institutional", url: "https://data.worldbank.org", platforms: [{ key: "wdi", name: "World Development Indicators", url: "https://datatopics.worldbank.org/world-development-indicators/", note: "Country indicators via the public API." }] },
  { key: "nasa", name: "NASA", tagline: "Earth observation and climate", tier: 1, kind: "scientific", url: "https://earthdata.nasa.gov", platforms: [{ key: "power", name: "POWER", url: "https://power.larc.nasa.gov", note: "Solar and meteorology climatology." }, { key: "gibs", name: "GIBS", url: "https://nasa-gibs.github.io/gibs-api-docs/", note: "Imagery tiles." }, { key: "firms", name: "FIRMS", url: "https://firms.modaps.eosdis.nasa.gov", note: "Active fires." }] },
  { key: "esa", name: "ESA", tagline: "European Space Agency land cover", tier: 1, kind: "scientific", url: "https://esa-worldcover.org", platforms: [{ key: "worldcover", name: "WorldCover", url: "https://esa-worldcover.org", note: "10 m global land cover." }] },
  { key: "copernicus", name: "Copernicus", tagline: "EU Earth observation programme", tier: 1, kind: "government", url: "https://dataspace.copernicus.eu", platforms: [{ key: "dem", name: "Copernicus DEM", url: "https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model", note: "GLO-30 elevation." }, { key: "sentinel", name: "Sentinel", url: "https://dataspace.copernicus.eu", note: "Sentinel imagery catalogue." }] },
  { key: "fao", name: "FAO", tagline: "Food and agriculture statistics", tier: 1, kind: "institutional", url: "https://www.fao.org/faostat", platforms: [{ key: "faostat", name: "FAOSTAT", url: "https://www.fao.org/faostat", note: "Agriculture statistics." }] },
  { key: "irena", name: "IRENA", tagline: "Renewable energy statistics", tier: 1, kind: "institutional", url: "https://www.irena.org/Data", platforms: [{ key: "stats", name: "IRENASTAT", url: "https://pxweb.irena.org", note: "Capacity and generation statistics." }] },
  { key: "osm", name: "OpenStreetMap", tagline: "Community-mapped infrastructure and places", tier: 1, kind: "open_community", url: "https://www.openstreetmap.org", platforms: [{ key: "overpass", name: "Overpass / OpenFreeMap", url: "https://overpass-api.de", note: "Infrastructure features and vector tiles." }] },
  { key: "protected_planet", name: "Protected Planet", tagline: "World Database on Protected Areas", tier: 1, kind: "institutional", url: "https://www.protectedplanet.net", platforms: [{ key: "wdpa", name: "WDPA", url: "https://www.protectedplanet.net", note: "Official protected areas. Commercial use needs a licence." }] },
  { key: "gbif", name: "GBIF", tagline: "Species occurrence records", tier: 1, kind: "scientific", url: "https://www.gbif.org", platforms: [{ key: "occurrence", name: "Occurrence API", url: "https://api.gbif.org", note: "Aggregated counts." }] },
  { key: "government", name: "Government datasets", tagline: "Jurisdictional data: grid operators, cadastres, environmental and water authorities", tier: 2, kind: "government", url: "https://data.gov", platforms: [{ key: "jurisdictional", name: "Jurisdictional sources", url: "https://data.gov", note: "Added per jurisdiction as Level 2 evidence." }] },
];

const WRI_CC = { license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", commercialUse: true, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true } as const;
const SCREEN = { evidenceLevel: 1 as const, screeningOnly: true, localValidationRequired: true, applicability: ["screening" as const] };

export const DATASETS: RegeneraDataset[] = [
  // ---------- WRI · Aqueduct ----------
  { id: "wri.aqueduct.baseline_water_stress", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Baseline water stress", category: "water", subcategory: "Water stress", sourceType: "api", adapter: "resource_watch",
    externalId: "aqueduct baseline water stress", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", apiUrl: "https://api.resourcewatch.org/v1", version: "4.0", geography: "Global (HydroBASINS level 6 sub-basins)",
    spatialResolution: "Sub-basin", temporalCoverage: "Baseline 1979–2019", ...WRI_CC, attributionText: "WRI Aqueduct 4.0 (Kuzma et al., 2023), CC BY 4.0", methodologyUrl: "https://www.wri.org/research/aqueduct-40-updated-decision-relevant-global-water-risk-indicators",
    ...SCREEN, analyticalRole: "Global screening of water availability pressure at basin scale", atlasGroup: "Water", atlasLayer: undefined,
    limitations: ["Sub-basin averages: not project-level hydrology", "Not a substitute for local hydrological and water-rights diligence", "Demand side modelled from sectoral estimates"] },
  { id: "wri.aqueduct.water_depletion", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Water depletion", category: "water", subcategory: "Depletion", sourceType: "api", adapter: "resource_watch", externalId: "aqueduct water depletion", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", version: "4.0", geography: "Global sub-basins", temporalCoverage: "Baseline", ...WRI_CC, attributionText: "WRI Aqueduct 4.0, CC BY 4.0", ...SCREEN, analyticalRole: "Share of renewable supply consumed", atlasGroup: "Water", limitations: ["Basin-scale; seasonal detail lost in annual figure"] },
  { id: "wri.aqueduct.seasonal_variability", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Seasonal variability", category: "water", sourceType: "api", adapter: "resource_watch", externalId: "aqueduct seasonal variability", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", version: "4.0", geography: "Global sub-basins", ...WRI_CC, attributionText: "WRI Aqueduct 4.0, CC BY 4.0", ...SCREEN, analyticalRole: "Within-year supply variability", atlasGroup: "Water", limitations: ["Screening indicator"] },
  { id: "wri.aqueduct.interannual_variability", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Interannual variability", category: "water", sourceType: "api", adapter: "resource_watch", externalId: "aqueduct interannual variability", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", version: "4.0", geography: "Global sub-basins", ...WRI_CC, attributionText: "WRI Aqueduct 4.0, CC BY 4.0", ...SCREEN, analyticalRole: "Year-to-year supply variability", atlasGroup: "Water", limitations: ["Screening indicator"] },
  { id: "wri.aqueduct.drought_risk", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Drought risk", category: "water", sourceType: "api", adapter: "resource_watch", externalId: "aqueduct drought risk", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", version: "4.0", geography: "Global", ...WRI_CC, attributionText: "WRI Aqueduct 4.0, CC BY 4.0", ...SCREEN, analyticalRole: "Drought hazard × exposure × vulnerability", atlasGroup: "Water", limitations: ["Composite index; component weights matter"] },
  { id: "wri.aqueduct.riverine_flood", provider: "wri", platform: "aqueduct", name: "Aqueduct Floods · Riverine flood hazard", category: "water", subcategory: "Flood", sourceType: "earth-engine", earthEngineAsset: "WRI/Aqueduct_Flood_Hazard_Maps/V2", sourceUrl: "https://www.wri.org/data/aqueduct-floods-hazard-maps", version: "2 (verify)", geography: "Global", spatialResolution: "≈1 km", scenarios: ["Baseline", "2030", "2050", "2080"], ...WRI_CC, attributionText: "WRI Aqueduct Floods, CC BY 4.0", ...SCREEN, analyticalRole: "Inundation depth by return period for screening", atlasGroup: "Water", limitations: ["≈1 km resolution misses local defences and drainage", "Not a flood study"] },
  { id: "wri.aqueduct.coastal_flood", provider: "wri", platform: "aqueduct", name: "Aqueduct Floods · Coastal flood hazard", category: "water", subcategory: "Flood", sourceType: "earth-engine", earthEngineAsset: "WRI/Aqueduct_Flood_Hazard_Maps/V2", sourceUrl: "https://www.wri.org/data/aqueduct-floods-hazard-maps", version: "2 (verify)", geography: "Global coasts", scenarios: ["Baseline", "2030", "2050", "2080"], ...WRI_CC, attributionText: "WRI Aqueduct Floods, CC BY 4.0", ...SCREEN, analyticalRole: "Coastal inundation screening incl. sea-level rise and subsidence scenarios", atlasGroup: "Water", limitations: ["Screening resolution"] },
  { id: "wri.aqueduct.future_water_stress", provider: "wri", platform: "aqueduct", name: "Aqueduct 4.0 · Future water stress, supply and demand", category: "water", sourceType: "api", adapter: "resource_watch", externalId: "aqueduct future water stress", sourceUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data", version: "4.0", geography: "Global sub-basins", scenarios: ["2030", "2050", "2080 · optimistic / business as usual / pessimistic"], ...WRI_CC, attributionText: "WRI Aqueduct 4.0, CC BY 4.0", ...SCREEN, analyticalRole: "Direction of change in water pressure under climate and socio-economic scenarios", atlasGroup: "Water", limitations: ["Scenario projections, not forecasts"] },
  // ---------- WRI · Global Forest Watch ----------
  { id: "wri.gfw.tree_cover_loss", provider: "wri", platform: "gfw", name: "Tree cover loss (Hansen / UMD)", category: "forest", sourceType: "api", adapter: "gfw", externalId: "umd_tree_cover_loss", sourceUrl: "https://www.globalforestwatch.org", apiUrl: "https://data-api.globalforestwatch.org", tileUrl: "tiles.globalforestwatch.org", earthEngineAsset: "UMD/hansen/global_forest_change_2023_v1_11", version: "latest annual release", geography: "Global", spatialResolution: "30 m", temporalCoverage: "2001 to latest year", ...WRI_CC, attributionText: "Hansen/UMD/Google/USGS/NASA, via Global Forest Watch, CC BY 4.0", envVar: "GFW_API_KEY",
    ...SCREEN, analyticalRole: "Historical stand-replacing loss within and around a site", atlasGroup: "Ecology", atlasLayer: "forest_loss", limitations: ["Loss includes plantation harvest and fire", "Tree cover ≠ natural forest"] },
  { id: "wri.gfw.tree_cover", provider: "wri", platform: "gfw", name: "Tree cover (2000 / 2010)", category: "forest", sourceType: "api", adapter: "gfw", externalId: "umd_tree_cover_density_2000", sourceUrl: "https://www.globalforestwatch.org", apiUrl: "https://data-api.globalforestwatch.org", geography: "Global", spatialResolution: "30 m", ...WRI_CC, attributionText: "Hansen/UMD via Global Forest Watch, CC BY 4.0", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Baseline canopy density", atlasGroup: "Ecology", limitations: ["Canopy density threshold choice changes results"] },
  { id: "wri.gfw.primary_forest", provider: "wri", platform: "gfw", name: "Humid tropical primary forest", category: "forest", sourceType: "api", adapter: "gfw", externalId: "umd_regional_primary_forest_2001", sourceUrl: "https://www.globalforestwatch.org", geography: "Humid tropics", spatialResolution: "30 m", ...WRI_CC, attributionText: "Turubanova et al. 2018 via GFW, CC BY 4.0", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Primary-forest intersection screening", atlasGroup: "Ecology", limitations: ["Humid tropics only"] },
  { id: "wri.gfw.forest_carbon_flux", provider: "wri", platform: "gfw", name: "Forest greenhouse gas net flux", category: "forest", sourceType: "api", adapter: "gfw", externalId: "gfw_forest_carbon_net_flux", sourceUrl: "https://www.globalforestwatch.org", geography: "Global", spatialResolution: "30 m", ...WRI_CC, attributionText: "Harris et al. 2021 via GFW, CC BY 4.0", envVar: "GFW_API_KEY", evidenceLevel: 1, screeningOnly: true, localValidationRequired: true, applicability: ["screening"], analyticalRole: "Carbon relevance of forest change", atlasGroup: "Ecology", limitations: ["Modelled flux; not a carbon-credit baseline"] },
  { id: "wri.gfw.concessions", provider: "wri", platform: "gfw", name: "Concessions (logging, mining, oil palm, oil and gas)", category: "land", subcategory: "Concessions", sourceType: "api", adapter: "gfw", externalId: "gfw_managed_forests / gfw_mining_concessions / gfw_oil_palm (verify slugs)", sourceUrl: "https://www.globalforestwatch.org", geography: "Selected countries", license: "Varies by country source", licenseUrl: "https://www.globalforestwatch.org/terms", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: null, attributionRequired: true, attributionText: "Source datasets via Global Forest Watch", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Overlap with known concessions", atlasGroup: "Land", limitations: ["Coverage and currency vary by country", "Not a legal tenure record"] },
  { id: "wri.gfw.fire_alerts", provider: "wri", platform: "gfw", name: "VIIRS fire alerts", category: "climate", subcategory: "Fire", sourceType: "api", adapter: "gfw", externalId: "nasa_viirs_fire_alerts", sourceUrl: "https://www.globalforestwatch.org", geography: "Global", ...WRI_CC, attributionText: "NASA FIRMS via Global Forest Watch", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Recent fire activity", atlasGroup: "Climate", atlasLayer: "fires", limitations: ["Thermal anomalies include industrial heat"] },
  { id: "wri.gfw.integrated_alerts", provider: "wri", platform: "gfw", name: "Integrated deforestation alerts", category: "forest", sourceType: "api", adapter: "gfw", externalId: "gfw_integrated_alerts", sourceUrl: "https://www.globalforestwatch.org", geography: "Tropics", ...WRI_CC, attributionText: "GLAD / RADD via Global Forest Watch", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Near-real-time disturbance", atlasGroup: "Ecology", limitations: ["Unconfirmed alerts are common"] },
  // ---------- WRI · Resource Watch ----------
  { id: "wri.rw.catalog", provider: "wri", platform: "resource_watch", name: "Resource Watch dataset catalogue", category: "economy", sourceType: "api", adapter: "resource_watch", sourceUrl: "https://resourcewatch.org/data/explore", apiUrl: "https://api.resourcewatch.org/v1/dataset", geography: "Global", license: "Per dataset (see each record)", licenseUrl: "https://resourcewatch.org/terms-of-service", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: true, attributionRequired: true, attributionText: "Resource Watch and the original data provider", ...SCREEN, analyticalRole: "Upstream catalogue for selective ingestion (climate, water, energy, air, population, agriculture)", atlasGroup: "Climate", limitations: ["Licence differs per dataset: always check the underlying source"] },
  // ---------- WRI · Energy Access Explorer ----------
  { id: "wri.eae.energy_access", provider: "wri", platform: "eae", name: "Energy Access Explorer · demand and supply layers", category: "energy", subcategory: "Energy access", sourceType: "manual", sourceUrl: "https://www.energyaccessexplorer.org", geography: "Selected countries (Africa, South Asia)", license: "Per country dataset (verify)", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: null, attributionRequired: true, attributionText: "WRI Energy Access Explorer and national data partners", ...SCREEN, analyticalRole: "Energy access opportunity: unserved population, social infrastructure, productive uses, grid proximity", atlasGroup: "Communities", limitations: ["Coverage limited to partner countries", "Layers are country-published; currency varies"] },
  // ---------- WRI · Land & Carbon Lab ----------
  { id: "wri.lcl.land_cover_change", provider: "wri", platform: "lcl", name: "Global land cover and land use change (GLAD)", category: "land", subcategory: "Land conversion", sourceType: "api", adapter: "gfw", externalId: "umd_glad_landsat_glclu (verify slug)", sourceUrl: "https://landcarbonlab.org", geography: "Global", spatialResolution: "30 m", temporalCoverage: "2000–2020", ...WRI_CC, attributionText: "Potapov et al. 2022 / Land & Carbon Lab, CC BY 4.0", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Observed conversion (cropland expansion, built-up, forest)", atlasGroup: "Land", limitations: ["Five-year steps"] },
  { id: "wri.lcl.tropical_tree_cover", provider: "wri", platform: "lcl", name: "Tropical tree cover (10 m)", category: "forest", sourceType: "api", adapter: "gfw", externalId: "wri_tropical_tree_cover", sourceUrl: "https://landcarbonlab.org", geography: "Tropics", spatialResolution: "10 m", ...WRI_CC, attributionText: "Brandt et al. / WRI Land & Carbon Lab, CC BY 4.0", envVar: "GFW_API_KEY", ...SCREEN, analyticalRole: "Trees outside forests, agroforestry and restoration baselines", atlasGroup: "Agriculture", limitations: ["Single-year snapshot"] },
  { id: "wri.lcl.carbon_removals", provider: "wri", platform: "lcl", name: "Carbon removal potential / restoration opportunity", category: "ecology", subcategory: "Restoration", sourceType: "download", sourceUrl: "https://landcarbonlab.org", geography: "Global", ...WRI_CC, attributionText: "WRI Land & Carbon Lab, CC BY 4.0", ...SCREEN, analyticalRole: "Where restoration could remove carbon", atlasGroup: "Ecology", limitations: ["Potential, not realised removals"] },
  // ---------- Other institutional providers already used by Regenera ----------
  { id: "wb.wdi", provider: "world_bank", platform: "wdi", name: "World Development Indicators", category: "economy", sourceType: "api", adapter: "wb_indicators", sourceUrl: "https://data.worldbank.org", apiUrl: "https://api.worldbank.org/v2", geography: "Countries", license: "CC BY 4.0", licenseUrl: "https://datacatalog.worldbank.org/public-licenses", commercialUse: true, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "Source: World Bank", ...SCREEN, analyticalRole: "Country context: access to electricity, population, income", atlasGroup: "Communities", limitations: ["Country level only"] },
  { id: "nasa.power", provider: "nasa", platform: "power", name: "POWER solar and meteorology", category: "energy", sourceType: "api", adapter: "nasa_power", sourceUrl: "https://power.larc.nasa.gov", geography: "Global", spatialResolution: "0.5° × 0.625°", license: "Public (NASA)", commercialUse: true, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "Cite NASA POWER", ...SCREEN, analyticalRole: "Solar, wind and climate screening", atlasGroup: "Energy", limitations: ["Coarse grid: not a bankable resource assessment"] },
  { id: "esa.worldcover", provider: "esa", platform: "worldcover", name: "ESA WorldCover 10 m", category: "land", sourceType: "download", sourceUrl: "https://esa-worldcover.org", geography: "Global", spatialResolution: "10 m", temporalCoverage: "2020, 2021", license: "CC BY 4.0", commercialUse: true, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "© ESA WorldCover project / Contains modified Copernicus Sentinel data", ...SCREEN, analyticalRole: "Land cover composition", atlasGroup: "Land", limitations: ["Classification accuracy varies by class"] },
  { id: "copernicus.dem", provider: "copernicus", platform: "dem", name: "Copernicus DEM GLO-30", category: "land", sourceType: "download", adapter: "copernicus_dem", sourceUrl: "https://spacedata.copernicus.eu", geography: "Global", spatialResolution: "30 m", license: "Copernicus DEM licence (free, attribution)", commercialUse: true, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "Copernicus DEM © DLR / Airbus, ESA", ...SCREEN, analyticalRole: "Elevation and slope screening", atlasGroup: "Land", limitations: ["Surface model: includes canopy and buildings"] },
  { id: "fao.faostat", provider: "fao", platform: "faostat", name: "FAOSTAT", category: "agriculture", sourceType: "api", sourceUrl: "https://www.fao.org/faostat", geography: "Countries", license: "CC BY 4.0 (verify per domain)", commercialUse: null, redistribution: true, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "Source: FAO", ...SCREEN, analyticalRole: "Agricultural production context", atlasGroup: "Agriculture", limitations: ["Country level"] },
  { id: "irena.stats", provider: "irena", platform: "stats", name: "IRENA renewable capacity statistics", category: "energy", sourceType: "download", sourceUrl: "https://www.irena.org/Data", geography: "Countries", license: "IRENA terms (verify)", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: true, attributionRequired: true, attributionText: "Source: IRENA", ...SCREEN, analyticalRole: "Country renewable build-out", atlasGroup: "Energy", limitations: ["Annual, country level"] },
  { id: "osm.infrastructure", provider: "osm", platform: "overpass", name: "OpenStreetMap infrastructure", category: "infrastructure", sourceType: "api", adapter: "overpass", sourceUrl: "https://www.openstreetmap.org", geography: "Global, uneven", license: "ODbL", licenseUrl: "https://www.openstreetmap.org/copyright", commercialUse: true, redistribution: false, derivatives: true, cacheAllowed: true, attributionRequired: true, attributionText: "© OpenStreetMap contributors", ...SCREEN, analyticalRole: "Roads, grid, water and settlements near a site", atlasGroup: "Infrastructure", atlasLayer: "power", limitations: ["Volunteer-mapped; absence of a feature is not evidence"] },
  { id: "wdpa.protected_areas", provider: "protected_planet", platform: "wdpa", name: "World Database on Protected Areas", category: "ecology", sourceType: "api", sourceUrl: "https://www.protectedplanet.net", geography: "Global", license: "Non-commercial without a licence", commercialUse: false, redistribution: false, derivatives: null, cacheAllowed: null, attributionRequired: true, attributionText: "UNEP-WCMC and IUCN, Protected Planet", envVar: "PROTECTED_PLANET_TOKEN", ...SCREEN, analyticalRole: "Protected-area proximity (official register)", atlasGroup: "Ecology", limitations: ["Commercial use needs an IBAT or WCMC licence; Regenera shows OSM protected tags instead until licensed"] },
  { id: "gbif.occurrences", provider: "gbif", platform: "occurrence", name: "GBIF species occurrences (aggregate)", category: "ecology", sourceType: "api", adapter: "gbif", sourceUrl: "https://www.gbif.org", geography: "Global", license: "Per record: CC0, CC BY or CC BY-NC", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: true, attributionRequired: true, attributionText: "GBIF.org and contributing datasets", ...SCREEN, analyticalRole: "Biodiversity recording density", atlasGroup: "Ecology", limitations: ["Sampling bias: records ≠ presence or absence"] },
  { id: "gov.jurisdictional", provider: "government", platform: "jurisdictional", name: "Jurisdictional datasets (per project)", category: "regulatory", sourceType: "manual", sourceUrl: "https://data.gov", geography: "Per jurisdiction", license: "Per source", commercialUse: null, redistribution: null, derivatives: null, cacheAllowed: null, attributionRequired: true, attributionText: "Per source", evidenceLevel: 2, screeningOnly: false, localValidationRequired: false, applicability: ["development"], analyticalRole: "Grid operator, cadastre, planning, environmental and water authority records", atlasGroup: "Regulatory", limitations: ["Recorded per project in the regulatory register"] },
];

export const providerOf = (key: string) => PROVIDERS.find(p => p.key === key);
export const datasetOf = (id: string) => DATASETS.find(d => d.id === id);

/** §15 Atlas layer library groups, in order. */
export const LAYER_LIBRARY: Record<string, string[]> = {
  Projects: ["Projects"],
  Energy: ["Grid", "Transmission", "Substations", "Solar", "Wind", "BESS", "Energy Access", "Demand", "Power Plants", "Data Centers"],
  Infrastructure: ["Roads", "Rail", "Ports", "Airports", "Pipelines", "Utilities"],
  Land: ["Parcels", "Land Cover", "Land Use", "Topography", "Elevation", "Concessions", "Land Conversion"],
  Water: ["Rivers", "Watersheds", "Water Stress", "Depletion", "Flood", "Drought", "Water Availability", "Future Water Risk"],
  Ecology: ["Forest", "Tree Cover Loss", "Protected Areas", "Biodiversity", "Carbon", "Restoration", "Habitat"],
  Agriculture: ["Cropland", "Soil", "Irrigation", "Agricultural Productivity", "Tree Crops", "Land Degradation"],
  Communities: ["Settlements", "Population", "Energy Access", "Health Facilities", "Schools", "Indigenous Territories", "TEK records (governed)"],
  Climate: ["Temperature", "Precipitation", "Wildfire", "Flood", "Drought", "Extreme Weather", "Climate Scenarios"],
  Regulatory: ["Planning Zones", "Permitting", "Energy Regulation", "Environmental Regulation", "Concessions"],
};
