// Integration registry seed (docs/plans/phase-6.md §7, docs/integration-licensing.md). Keys match the `provider`
// strings used by lib/sources and the provider_calls ledger. Terms are as understood when written; "verify" notes
// mark those to re-check before production use. A public API is not an unrestricted commercial licence.

export type FeatureState = "enabled" | "development_only" | "license_required" | "disabled";
export type IntegrationSeed = {
  key: string; provider: string; dataset: string; category: string; coverage: string; baseUrl: string;
  auth: "none" | "key" | "account" | "oauth"; envVar?: string; license: string; licenseUrl?: string;
  commercialUse: "yes" | "conditional" | "no" | "verify"; attribution: string; caching: string; redistribution: string;
  rateLimit: string; refresh: string; featureState: FeatureState; tier: 1 | 2 | 3 | 4 | 5; notes?: string;
};

export const INTEGRATIONS: IntegrationSeed[] = [
  // In use
  { key: "gleif", provider: "GLEIF", dataset: "LEI records", category: "Corporate", coverage: "Global", baseUrl: "https://api.gleif.org/api/v1", auth: "none", license: "CC0 1.0", licenseUrl: "https://www.gleif.org/en/meta/lei-data-terms-of-use", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "60 req/min", refresh: "On enrichment", featureState: "enabled", tier: 1 },
  { key: "edgar", provider: "SEC EDGAR", dataset: "Company submissions, Form D", category: "Corporate / filings", coverage: "US", baseUrl: "https://data.sec.gov", auth: "none", license: "Public domain (US government)", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "10 req/s, User-Agent with contact required", refresh: "Every scan", featureState: "enabled", tier: 1 },
  { key: "wikidata", provider: "Wikidata", dataset: "Entities", category: "Corporate", coverage: "Global", baseUrl: "https://www.wikidata.org", auth: "none", license: "CC0 1.0", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "On enrichment", featureState: "enabled", tier: 4 },
  { key: "gdelt", provider: "GDELT", dataset: "DOC 2.0 news", category: "Intelligence", coverage: "Global", baseUrl: "https://api.gdeltproject.org", auth: "none", license: "Open, attribution requested", commercialUse: "yes", attribution: "Cite GDELT", caching: "Allowed", redistribution: "Links only", rateLimit: "1 request / 5 s", refresh: "Every 15 min", featureState: "enabled", tier: 4 },
  { key: "gdacs", provider: "GDACS", dataset: "Disaster alerts", category: "Hazards", coverage: "Global", baseUrl: "https://www.gdacs.org", auth: "none", license: "Free use with attribution (verify)", commercialUse: "verify", attribution: "GDACS / EC JRC", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Hourly", featureState: "enabled", tier: 2 },
  { key: "ted", provider: "EU TED", dataset: "Tenders", category: "Funding / procurement", coverage: "EU", baseUrl: "https://api.ted.europa.eu", auth: "none", license: "EU reuse policy", commercialUse: "yes", attribution: "Source: TED", caching: "Allowed", redistribution: "Allowed with source", rateLimit: "Fair use", refresh: "Every 2 h", featureState: "enabled", tier: 1 },
  { key: "eu_funding", provider: "EU Funding & Tenders", dataset: "Calls for proposals", category: "Funding", coverage: "EU programmes", baseUrl: "https://api.tech.ec.europa.eu", auth: "none", license: "EU reuse policy", commercialUse: "yes", attribution: "Source: European Commission", caching: "Allowed", redistribution: "Allowed with source", rateLimit: "Fair use", refresh: "Every 2 h", featureState: "enabled", tier: 1 },
  { key: "worldbank", provider: "World Bank", dataset: "Procurement notices", category: "Funding / procurement", coverage: "World Bank projects", baseUrl: "https://search.worldbank.org/api", auth: "none", license: "CC BY 4.0", commercialUse: "yes", attribution: "Source: World Bank", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Every 2 h", featureState: "enabled", tier: 2 },
  { key: "grants_gov", provider: "Grants.gov", dataset: "Grant opportunities", category: "Funding", coverage: "US federal", baseUrl: "https://api.grants.gov/v1", auth: "none", license: "Public (US government)", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Every 2 h", featureState: "enabled", tier: 1 },
  { key: "uk_contracts", provider: "UK Contracts Finder", dataset: "OCDS notices", category: "Funding / procurement", coverage: "UK", baseUrl: "https://www.contractsfinder.service.gov.uk", auth: "none", license: "Open Government Licence v3", commercialUse: "yes", attribution: "Contains public sector information licensed under the OGL", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Every 2 h", featureState: "enabled", tier: 1 },
  { key: "nominatim", provider: "OpenStreetMap Nominatim", dataset: "Geocoding", category: "Map", coverage: "Global", baseUrl: "https://nominatim.openstreetmap.org", auth: "none", license: "ODbL (data); usage policy", licenseUrl: "https://operations.osmfoundation.org/policies/nominatim/", commercialUse: "conditional", attribution: "© OpenStreetMap contributors", caching: "Required", redistribution: "ODbL share-alike", rateLimit: "1 req/s, no bulk", refresh: "On demand", featureState: "development_only", tier: 3, notes: "Low-volume only: 1 req/s, cached 90 days, never autocomplete or bulk (OSMF policy). Set NOMINATIM_URL to a self-hosted instance for production volume." },
  { key: "apollo", provider: "Apollo.io", dataset: "People and company search", category: "Prospect data", coverage: "Global", baseUrl: "https://api.apollo.io", auth: "key", envVar: "APOLLO_API_KEY", license: "Account terms", commercialUse: "conditional", attribution: "Not required", caching: "Per terms", redistribution: "No", rateLimit: "Plan limits", refresh: "On demand", featureState: "enabled", tier: 3 },
  { key: "sbti", provider: "SBTi", dataset: "Companies taking action", category: "Lists", coverage: "Global", baseUrl: "https://sciencebasedtargets.org", auth: "none", license: "Published file (verify terms)", commercialUse: "verify", attribution: "Source: SBTi", caching: "Allowed", redistribution: "No", rateLimit: "Weekly", refresh: "Weekly", featureState: "enabled", tier: 3 },
  { key: "esri", provider: "Esri World Imagery", dataset: "Basemap tiles (sub-metre imagery)", category: "Map", coverage: "Global", baseUrl: "https://server.arcgisonline.com", auth: "none", envVar: "ESRI_API_KEY", license: "Esri terms of use; a free ArcGIS Location Platform key (ESRI_API_KEY) moves tiles to the metered production endpoint", commercialUse: "conditional", attribution: "Imagery © Esri, Maxar, Earthstar Geographics, and the GIS User Community", caching: "No (browser only)", redistribution: "No", rateLimit: "Fair use without a key; plan limits with one", refresh: "Periodic", featureState: "enabled", tier: 3, notes: "Displayed as a basemap in the browser only; never downloaded, stored or redistributed." },
  // Ready (free, no key): used by the place profile
  { key: "nasa_power", provider: "NASA POWER", dataset: "Solar and meteorology (climatology)", category: "Climate / solar", coverage: "Global", baseUrl: "https://power.larc.nasa.gov/api", auth: "none", license: "Public (NASA)", licenseUrl: "https://power.larc.nasa.gov/docs/referencing/", commercialUse: "yes", attribution: "Cite NASA POWER", caching: "Allowed", redistribution: "With citation", rateLimit: "Fair use", refresh: "On request (climatology)", featureState: "enabled", tier: 2 },
  { key: "wb_indicators", provider: "World Bank Indicators", dataset: "World Development Indicators", category: "Country", coverage: "Global", baseUrl: "https://api.worldbank.org/v2", auth: "none", license: "CC BY 4.0", licenseUrl: "https://datacatalog.worldbank.org/public-licenses", commercialUse: "yes", attribution: "Source: World Bank", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Quarterly", featureState: "enabled", tier: 2 },
  { key: "overpass", provider: "OpenStreetMap Overpass", dataset: "Infrastructure features", category: "Place / infrastructure", coverage: "Global", baseUrl: "https://overpass-api.de/api", auth: "none", license: "ODbL", licenseUrl: "https://www.openstreetmap.org/copyright", commercialUse: "conditional", attribution: "© OpenStreetMap contributors", caching: "Required", redistribution: "ODbL share-alike for derived databases", rateLimit: "Fair use on public instances", refresh: "Monthly", featureState: "enabled", tier: 3 },
  { key: "usgs_quakes", provider: "USGS Earthquakes", dataset: "Earthquake catalog", category: "Hazards", coverage: "Global", baseUrl: "https://earthquake.usgs.gov/fdsnws/event/1", auth: "none", license: "Public domain (US government)", commercialUse: "yes", attribution: "Source: USGS", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Monthly", featureState: "enabled", tier: 1 },
  { key: "gbif", provider: "GBIF", dataset: "Species occurrences", category: "Biodiversity", coverage: "Global", baseUrl: "https://api.gbif.org/v1", auth: "none", license: "Per dataset: CC0, CC BY or CC BY-NC", licenseUrl: "https://www.gbif.org/terms", commercialUse: "conditional", attribution: "Cite GBIF and datasets", caching: "Allowed", redistribution: "Per record licence; exclude CC BY-NC from commercial outputs", rateLimit: "Fair use", refresh: "Quarterly", featureState: "enabled", tier: 2 },
  { key: "natural_earth", provider: "Natural Earth", dataset: "Boundaries", category: "Map", coverage: "Global", baseUrl: "https://www.naturalearthdata.com", auth: "none", license: "Public domain", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "Download", refresh: "Rare", featureState: "development_only", tier: 3 },
  { key: "usaspending", provider: "USAspending", dataset: "Federal awards", category: "Funding", coverage: "US", baseUrl: "https://api.usaspending.gov", auth: "none", license: "Public", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Daily", featureState: "development_only", tier: 1 },
  { key: "usgs_water", provider: "USGS Water", dataset: "Water data", category: "Water", coverage: "US", baseUrl: "https://waterservices.usgs.gov", auth: "none", license: "Public domain", commercialUse: "yes", attribution: "Source: USGS", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Daily", featureState: "development_only", tier: 1 },
  { key: "epa_envirofacts", provider: "EPA Envirofacts", dataset: "Facilities", category: "Environment", coverage: "US", baseUrl: "https://data.epa.gov/efservice", auth: "none", license: "Public", commercialUse: "yes", attribution: "Source: US EPA", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Monthly", featureState: "development_only", tier: 1 },
  { key: "openalex", provider: "OpenAlex", dataset: "Research works", category: "Research", coverage: "Global", baseUrl: "https://api.openalex.org", auth: "none", license: "CC0", commercialUse: "yes", attribution: "Appreciated", caching: "Allowed", redistribution: "Allowed", rateLimit: "100k/day, polite pool with email", refresh: "On demand", featureState: "development_only", tier: 2 },
  { key: "crossref", provider: "Crossref", dataset: "Metadata", category: "Research", coverage: "Global", baseUrl: "https://api.crossref.org", auth: "none", license: "Metadata mostly CC0", commercialUse: "yes", attribution: "Appreciated", caching: "Allowed", redistribution: "Allowed", rateLimit: "Polite pool with mailto", refresh: "On demand", featureState: "development_only", tier: 2 },
  { key: "eurostat", provider: "Eurostat", dataset: "Statistics", category: "Country", coverage: "EU", baseUrl: "https://ec.europa.eu/eurostat/api", auth: "none", license: "Free reuse with attribution", commercialUse: "yes", attribution: "Source: Eurostat", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Quarterly", featureState: "development_only", tier: 1 },
  { key: "faostat", provider: "FAOSTAT", dataset: "Agriculture", category: "Agriculture", coverage: "Global", baseUrl: "https://www.fao.org/faostat", auth: "none", license: "CC BY 4.0 (verify)", commercialUse: "verify", attribution: "Source: FAO", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Annual", featureState: "development_only", tier: 2 },
  // Free credential needed
  { key: "nrel", provider: "NREL (NLR) developer APIs", dataset: "PVWatts V8, NSRDB", category: "Energy", coverage: "Global (PVWatts), Americas (NSRDB)", baseUrl: "https://developer.nrel.gov/api", auth: "key", envVar: "NREL_API_KEY", license: "Public; API terms", commercialUse: "yes", attribution: "Cite NREL", caching: "Allowed", redistribution: "With citation", rateLimit: "1,000 req/h per key", refresh: "On request", featureState: "development_only", tier: 1, notes: "Integration ready: credential required." },
  { key: "eia", provider: "EIA Open Data", dataset: "Energy statistics", category: "Energy", coverage: "US / international", baseUrl: "https://api.eia.gov/v2", auth: "key", envVar: "EIA_API_KEY", license: "Public domain", commercialUse: "yes", attribution: "Source: EIA", caching: "Allowed", redistribution: "Allowed", rateLimit: "Per key", refresh: "Daily", featureState: "development_only", tier: 1, notes: "Integration ready: credential required." },
  { key: "fred", provider: "FRED", dataset: "Economic series", category: "Markets", coverage: "Global series", baseUrl: "https://api.stlouisfed.org/fred", auth: "key", envVar: "FRED_API_KEY", license: "FRED terms; some series third-party copyright", commercialUse: "conditional", attribution: "Source: FRED", caching: "Per terms", redistribution: "Per series", rateLimit: "120 req/min", refresh: "Daily", featureState: "development_only", tier: 2 },
  { key: "companies_house", provider: "Companies House", dataset: "UK company register", category: "Corporate", coverage: "UK", baseUrl: "https://api.company-information.service.gov.uk", auth: "key", envVar: "COMPANIES_HOUSE_API_KEY", license: "Open Government Licence", commercialUse: "yes", attribution: "Contains public sector information licensed under the OGL", caching: "Allowed", redistribution: "With attribution", rateLimit: "600 req / 5 min", refresh: "On enrichment", featureState: "development_only", tier: 1 },
  { key: "sam_gov", provider: "SAM.gov", dataset: "Contract opportunities", category: "Funding", coverage: "US federal", baseUrl: "https://api.sam.gov", auth: "key", envVar: "SAM_API_KEY", license: "Public", commercialUse: "yes", attribution: "Not required", caching: "Allowed", redistribution: "Allowed", rateLimit: "Per key", refresh: "Daily", featureState: "disabled", tier: 1, notes: "Skipped: Grants.gov covers US grants." },
  { key: "copernicus", provider: "Copernicus Data Space", dataset: "Sentinel imagery (STAC, OData, openEO)", category: "Earth observation", coverage: "Global", baseUrl: "https://dataspace.copernicus.eu", auth: "account", envVar: "COPERNICUS_CLIENT_ID", license: "Copernicus free and open data licence", commercialUse: "yes", attribution: "Contains modified Copernicus Sentinel data", caching: "Allowed", redistribution: "With attribution", rateLimit: "Account quotas", refresh: "Per scene", featureState: "development_only", tier: 2, notes: "Processing stays with the provider (openEO), not the Worker." },
  { key: "gfw", provider: "Global Forest Watch", dataset: "Tree cover loss, alerts", category: "Forest", coverage: "Global", baseUrl: "https://data-api.globalforestwatch.org", auth: "key", envVar: "GFW_API_KEY", license: "Mostly CC BY 4.0, varies by dataset (verify)", commercialUse: "verify", attribution: "Source: Global Forest Watch", caching: "Allowed", redistribution: "Per dataset", rateLimit: "Per key", refresh: "Monthly", featureState: "development_only", tier: 2 },
  { key: "openaq", provider: "OpenAQ", dataset: "Air quality", category: "Environment", coverage: "Global", baseUrl: "https://api.openaq.org/v3", auth: "key", envVar: "OPENAQ_API_KEY", license: "Mostly CC BY 4.0, per source (verify)", commercialUse: "verify", attribution: "Source: OpenAQ and providers", caching: "Allowed", redistribution: "Per source", rateLimit: "Per key", refresh: "Daily", featureState: "development_only", tier: 3 },
  { key: "entsoe", provider: "ENTSO-E Transparency", dataset: "European grid data", category: "Grid", coverage: "Europe", baseUrl: "https://web-api.tp.entsoe.eu", auth: "key", envVar: "ENTSOE_TOKEN", license: "ENTSO-E terms of use", commercialUse: "conditional", attribution: "Source: ENTSO-E", caching: "Per terms", redistribution: "Per terms", rateLimit: "400 req/min", refresh: "Hourly", featureState: "development_only", tier: 1 },
  { key: "comtrade", provider: "UN Comtrade", dataset: "Trade flows", category: "Trade", coverage: "Global", baseUrl: "https://comtradeapi.un.org", auth: "key", envVar: "COMTRADE_API_KEY", license: "Free tier limited; bulk by subscription", commercialUse: "conditional", attribution: "Source: UN Comtrade", caching: "Per terms", redistribution: "No", rateLimit: "Free tier quota", refresh: "Monthly", featureState: "development_only", tier: 2 },
  { key: "irena_ember", provider: "IRENA / Ember", dataset: "Energy transition data", category: "Energy", coverage: "Global", baseUrl: "https://ember-energy.org", auth: "none", license: "Ember CC BY 4.0; IRENA terms (verify)", commercialUse: "verify", attribution: "Source: Ember / IRENA", caching: "Allowed", redistribution: "With attribution", rateLimit: "Download", refresh: "Annual", featureState: "development_only", tier: 2 },
  // Licence required before production
  { key: "open_meteo", provider: "Open-Meteo", dataset: "Weather forecasts", category: "Weather", coverage: "Global", baseUrl: "https://api.open-meteo.com", auth: "none", license: "Free tier non-commercial; commercial plan required", commercialUse: "no", attribution: "Weather data by Open-Meteo.com", caching: "Allowed", redistribution: "CC BY 4.0 data", rateLimit: "10k/day free", refresh: "Hourly", featureState: "license_required", tier: 3 },
  { key: "wdpa", provider: "Protected Planet (WDPA)", dataset: "Protected areas", category: "Biodiversity", coverage: "Global", baseUrl: "https://api.protectedplanet.net", auth: "key", envVar: "PROTECTED_PLANET_TOKEN", license: "Non-commercial without a licence", commercialUse: "no", attribution: "UNEP-WCMC and IUCN", caching: "Per terms", redistribution: "No", rateLimit: "Per token", refresh: "Monthly", featureState: "license_required", tier: 2 },
  { key: "ibat", provider: "IUCN / IBAT", dataset: "Biodiversity risk screening", category: "Biodiversity", coverage: "Global", baseUrl: "https://www.ibat-alliance.org", auth: "account", license: "Paid subscription", commercialUse: "conditional", attribution: "Per licence", caching: "Per licence", redistribution: "No", rateLimit: "Per licence", refresh: "Per licence", featureState: "license_required", tier: 2 },
  { key: "ec3", provider: "Building Transparency EC3", dataset: "EPDs and embodied carbon", category: "Materials", coverage: "Global", baseUrl: "https://buildingtransparency.org/api", auth: "account", license: "Account terms (verify commercial use)", commercialUse: "verify", attribution: "Source: EC3", caching: "Per terms", redistribution: "No", rateLimit: "Per account", refresh: "On request", featureState: "license_required", tier: 3 },
  { key: "opencorporates", provider: "OpenCorporates", dataset: "Company registries", category: "Corporate", coverage: "Global", baseUrl: "https://api.opencorporates.com", auth: "key", envVar: "OPENCORPORATES_API_KEY", license: "ODbL share-alike or paid licence", commercialUse: "conditional", attribution: "Source: OpenCorporates", caching: "Per licence", redistribution: "Share-alike", rateLimit: "Per plan", refresh: "On enrichment", featureState: "license_required", tier: 3 },
  // Added in the master build (2026-09-26): adapters in lib/integrations/adapters.ts
  { key: "nominatim_self", provider: "Self-hosted Nominatim", dataset: "Geocoding", category: "Map", coverage: "Global (your import)", baseUrl: "NOMINATIM_URL", auth: "none", envVar: "NOMINATIM_URL", license: "ODbL (data)", commercialUse: "yes", attribution: "© OpenStreetMap contributors", caching: "Allowed", redistribution: "ODbL share-alike", rateLimit: "Your instance", refresh: "On demand", featureState: "development_only", tier: 3, notes: "Integration ready: set NOMINATIM_URL." },
  { key: "pvgis", provider: "PVGIS (EU JRC)", dataset: "PV potential, irradiation, TMY", category: "Climate / solar", coverage: "Europe, Africa, Asia, Americas", baseUrl: "https://re.jrc.ec.europa.eu/api/v5_3", auth: "none", license: "Free use with attribution (EU JRC)", licenseUrl: "https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en", commercialUse: "yes", attribution: "PVGIS © European Union", caching: "Allowed", redistribution: "With attribution", rateLimit: "30 req/s per IP (server-side only)", refresh: "Yearly", featureState: "enabled", tier: 1 },
  { key: "copernicus_stac", provider: "Copernicus Data Space STAC", dataset: "Sentinel scene catalogue", category: "Earth observation", coverage: "Global", baseUrl: "https://stac.dataspace.copernicus.eu/v1", auth: "none", envVar: "COPERNICUS_STAC_URL", license: "Copernicus free and open data licence", commercialUse: "yes", attribution: "Contains modified Copernicus Sentinel data", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "On request", featureState: "enabled", tier: 2, notes: "Metadata only; no automatic raster downloads." },
  { key: "noaa_cdo", provider: "NOAA NCEI Climate Data Online", dataset: "Station climate data", category: "Climate", coverage: "Global stations", baseUrl: "https://www.ncei.noaa.gov/cdo-web/api/v2", auth: "key", envVar: "NOAA_CDO_TOKEN", license: "Public (US government)", commercialUse: "yes", attribution: "Source: NOAA NCEI", caching: "Allowed", redistribution: "Allowed", rateLimit: "5 req/s, 10,000/day", refresh: "Monthly", featureState: "development_only", tier: 1, notes: "Integration ready: credential required." },
  { key: "nasa_firms", provider: "NASA FIRMS", dataset: "Active fire detections (VIIRS/MODIS)", category: "Hazards", coverage: "Global", baseUrl: "https://firms.modaps.eosdis.nasa.gov/api", auth: "key", envVar: "NASA_FIRMS_MAP_KEY", license: "Open (NASA); cite FIRMS", commercialUse: "yes", attribution: "NASA FIRMS", caching: "Allowed", redistribution: "With citation", rateLimit: "5,000 transactions / 10 min", refresh: "3-hourly", featureState: "development_only", tier: 2, notes: "Integration ready: credential required." },
  { key: "imf", provider: "IMF SDMX", dataset: "Macroeconomic series (IFS, WEO)", category: "Country", coverage: "Global", baseUrl: "https://dataservices.imf.org/REST/SDMX_JSON.svc", auth: "none", envVar: "IMF_SDMX_URL", license: "IMF terms (free reuse with attribution; verify)", commercialUse: "verify", attribution: "Source: IMF", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Monthly", featureState: "development_only", tier: 2, notes: "The IMF is migrating its data API; base URL is configurable (IMF_SDMX_URL)." },
  { key: "ercot", provider: "ERCOT Public API", dataset: "Texas grid and market data", category: "Grid", coverage: "Texas", baseUrl: "https://api.ercot.com/api/public-reports", auth: "account", envVar: "ERCOT_SUBSCRIPTION_KEY", license: "ERCOT API terms", commercialUse: "conditional", attribution: "Source: ERCOT", caching: "Per terms", redistribution: "Per terms", rateLimit: "30 req/min", refresh: "Daily", featureState: "disabled", tier: 1, notes: "Adapter pending an account (subscription key + ID token)." },
  { key: "caiso", provider: "CAISO OASIS", dataset: "California market data", category: "Grid", coverage: "California", baseUrl: "http://oasis.caiso.com/oasisapi", auth: "none", license: "CAISO terms", commercialUse: "conditional", attribution: "Source: CAISO", caching: "Allowed", redistribution: "Per terms", rateLimit: "1 req / 5 s", refresh: "Daily", featureState: "disabled", tier: 1, notes: "Returns zipped XML/CSV; use manual import until a project needs it." },
  { key: "pjm", provider: "PJM Data Miner", dataset: "PJM market data", category: "Grid", coverage: "PJM", baseUrl: "https://api.pjm.com", auth: "key", envVar: "PJM_API_KEY", license: "PJM terms: redistribution restricted", commercialUse: "conditional", attribution: "Source: PJM", caching: "Per terms", redistribution: "Restricted", rateLimit: "Per key", refresh: "Daily", featureState: "license_required", tier: 1 },
  { key: "soilgrids", provider: "ISRIC SoilGrids", dataset: "Soil properties", category: "Land", coverage: "Global", baseUrl: "https://rest.isric.org", auth: "none", license: "CC BY 4.0", commercialUse: "yes", attribution: "ISRIC SoilGrids", caching: "Allowed", redistribution: "With attribution", rateLimit: "Paused", refresh: "Static", featureState: "disabled", tier: 2, notes: "REST service paused by ISRIC; use downloaded rasters via Atlas import." },
  { key: "google_places", provider: "Google Places", dataset: "Places, geocoding", category: "Map", coverage: "Global", baseUrl: "https://places.googleapis.com", auth: "key", envVar: "GOOGLE_MAPS_API_KEY", license: "Google Maps Platform terms (paid)", commercialUse: "conditional", attribution: "Google", caching: "Restricted", redistribution: "No", rateLimit: "Billing quotas", refresh: "On demand", featureState: "disabled", tier: 3, notes: "Optional paid provider; ask before enabling." },
  { key: "google_solar", provider: "Google Solar API", dataset: "Rooftop solar potential", category: "Climate / solar", coverage: "Supported cities (rooftops)", baseUrl: "https://solar.googleapis.com", auth: "key", envVar: "GOOGLE_MAPS_API_KEY", license: "Google Maps Platform terms (paid)", commercialUse: "conditional", attribution: "Google", caching: "Restricted", redistribution: "No", rateLimit: "Billing quotas", refresh: "On demand", featureState: "disabled", tier: 3, notes: "Rooftops only; not a utility-scale resource source." },
  { key: "docusign", provider: "DocuSign", dataset: "E-signature", category: "E-signature", coverage: "Global", baseUrl: "https://account.docusign.com", auth: "oauth", envVar: "DOCUSIGN_CLIENT_ID", license: "Account terms (paid)", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "Per plan", refresh: "Webhook", featureState: "disabled", tier: 3, notes: "Signed-PDF upload is the fallback; mock provider in development." },
  { key: "dropbox_sign", provider: "Dropbox Sign", dataset: "E-signature", category: "E-signature", coverage: "Global", baseUrl: "https://api.hellosign.com/v3", auth: "key", envVar: "DROPBOX_SIGN_API_KEY", license: "Account terms (paid)", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "Per plan", refresh: "Webhook", featureState: "disabled", tier: 3 },
  { key: "stripe", provider: "Stripe", dataset: "Payments", category: "Commercial", coverage: "Global", baseUrl: "https://api.stripe.com", auth: "key", envVar: "STRIPE_SECRET_KEY", license: "Account terms (paid per transaction)", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "Per account", refresh: "Webhook", featureState: "disabled", tier: 3 },
  { key: "quickbooks", provider: "QuickBooks", dataset: "Accounting", category: "Commercial", coverage: "Global", baseUrl: "https://quickbooks.api.intuit.com", auth: "oauth", license: "Account terms (paid)", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "Per plan", refresh: "Daily", featureState: "disabled", tier: 3 },
  { key: "xero", provider: "Xero", dataset: "Accounting", category: "Commercial", coverage: "Global", baseUrl: "https://api.xero.com", auth: "oauth", license: "Account terms (paid)", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "60 req/min", refresh: "Daily", featureState: "disabled", tier: 3 },
  { key: "sentry", provider: "Sentry", dataset: "Error monitoring", category: "Operations", coverage: "n/a", baseUrl: "https://sentry.io", auth: "key", envVar: "SENTRY_DSN", license: "Account terms", commercialUse: "yes", attribution: "Not required", caching: "n/a", redistribution: "n/a", rateLimit: "Per plan", refresh: "Live", featureState: "disabled", tier: 3 },
  // Atlas live intelligence (lib/map/catalog.ts): browser tiles and server-proxied feeds on the 3D globe
  { key: "nasa_gibs", provider: "NASA GIBS", dataset: "Daily satellite imagery, night lights, NDVI, land surface temperature, precipitation, aerosol", category: "Earth observation", coverage: "Global", baseUrl: "https://gibs.earthdata.nasa.gov/wmts", auth: "none", license: "NASA open data (no restriction)", licenseUrl: "https://www.earthdata.nasa.gov/engage/open-data-services-software-policies", commercialUse: "yes", attribution: "Imagery: NASA EOSDIS GIBS", caching: "Allowed", redistribution: "Allowed with credit", rateLimit: "Fair use", refresh: "Daily", featureState: "enabled", tier: 1 },
  { key: "nasa_eonet", provider: "NASA EONET", dataset: "Natural events (storms, wildfires, volcanoes, floods, ice)", category: "Hazards", coverage: "Global", baseUrl: "https://eonet.gsfc.nasa.gov/api/v3", auth: "none", license: "NASA open data", commercialUse: "yes", attribution: "Source: NASA EONET", caching: "Allowed", redistribution: "Allowed with credit", rateLimit: "Fair use", refresh: "Hourly", featureState: "enabled", tier: 2 },
  { key: "noaa_nhc", provider: "NOAA National Hurricane Center", dataset: "Active tropical cyclones", category: "Hazards", coverage: "Atlantic, eastern and central Pacific", baseUrl: "https://www.nhc.noaa.gov", auth: "none", license: "Public domain (US government)", commercialUse: "yes", attribution: "Source: NOAA NHC", caching: "Allowed", redistribution: "Allowed", rateLimit: "Fair use", refresh: "Every 30 min", featureState: "enabled", tier: 1 },
  { key: "nasa_firms_public", provider: "NASA FIRMS (public files)", dataset: "Active fires, MODIS global 24 h", category: "Hazards", coverage: "Global", baseUrl: "https://firms.modaps.eosdis.nasa.gov/data/active_fire", auth: "none", license: "Open (NASA); cite FIRMS", commercialUse: "yes", attribution: "NASA FIRMS", caching: "Allowed", redistribution: "With citation", rateLimit: "Fair use", refresh: "Every 3 h", featureState: "enabled", tier: 1, notes: "Keyless fallback. With NASA_FIRMS_MAP_KEY the Atlas uses the VIIRS 375 m area API for the view instead." },
  { key: "adsb_lol", provider: "adsb.lol", dataset: "Live aircraft (ADS-B), military traffic", category: "Movement", coverage: "Global receiver network", baseUrl: "https://api.adsb.lol/v2", auth: "none", license: "ODbL 1.0", licenseUrl: "https://www.adsb.lol/docs/open-data/api/", commercialUse: "yes", attribution: "Aircraft data: adsb.lol (ODbL)", caching: "Allowed", redistribution: "ODbL share-alike", rateLimit: "Fair use; per-view radius ≤ 250 nm", refresh: "Every 15 s", featureState: "enabled", tier: 3, notes: "Community receivers: coverage gaps are not absence of aircraft." },
  { key: "celestrak", provider: "CelesTrak", dataset: "Orbital elements (GP / OMM)", category: "Space", coverage: "Global", baseUrl: "https://celestrak.org/NORAD/elements", auth: "none", license: "Free use with credit", commercialUse: "yes", attribution: "Orbital data: CelesTrak", caching: "Required (no more than once per 2 h per group)", redistribution: "With credit", rateLimit: "Once per update, 2 h", refresh: "Every 6 h", featureState: "enabled", tier: 2, notes: "Positions are SGP4 propagations in the browser (satellite.js), not observations." },
  { key: "eox_s2cloudless", provider: "EOX Sentinel-2 cloudless", dataset: "Sentinel-2 cloudless mosaic 2016 (10 m)", category: "Map", coverage: "Global", baseUrl: "https://tiles.maps.eox.at/wmts", auth: "none", license: "CC BY 4.0 (2016 mosaic only; later years CC BY-NC-SA)", licenseUrl: "https://s2maps.eu", commercialUse: "yes", attribution: "Sentinel-2 cloudless by EOX IT Services GmbH (contains modified Copernicus Sentinel data 2016)", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Static", featureState: "enabled", tier: 2 },
  { key: "gfw_tiles", provider: "Global Forest Watch tiles", dataset: "Tree cover loss (Hansen/UMD)", category: "Forest", coverage: "Global", baseUrl: "https://tiles.globalforestwatch.org", auth: "none", license: "CC BY 4.0", licenseUrl: "https://www.globalforestwatch.org/terms", commercialUse: "yes", attribution: "Hansen/UMD/Google/USGS/NASA via Global Forest Watch", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Annual", featureState: "enabled", tier: 1 },
  { key: "openfreemap", provider: "OpenFreeMap", dataset: "OpenStreetMap vector tiles (boundaries, places, buildings, parks)", category: "Map", coverage: "Global", baseUrl: "https://tiles.openfreemap.org", auth: "none", license: "ODbL (data), free service", licenseUrl: "https://openfreemap.org", commercialUse: "yes", attribution: "© OpenStreetMap contributors, OpenFreeMap", caching: "Allowed", redistribution: "ODbL", rateLimit: "No limits stated", refresh: "Weekly", featureState: "enabled", tier: 3 },
  { key: "openinframap", provider: "Open Infrastructure Map", dataset: "Power lines, plants, substations (OSM)", category: "Place / infrastructure", coverage: "Global", baseUrl: "https://openinframap.org/tiles", auth: "none", license: "ODbL (OSM data)", licenseUrl: "https://openinframap.org/about", commercialUse: "conditional", attribution: "Open Infrastructure Map, © OpenStreetMap contributors", caching: "Per service policy", redistribution: "ODbL", rateLimit: "Light use of the public tile server", refresh: "Daily", featureState: "enabled", tier: 3, notes: "Community-mapped: incomplete by nature. Self-host the tiles for heavy production use." },
  { key: "aws_terrain", provider: "AWS Terrain Tiles (Mapzen)", dataset: "Elevation (terrarium)", category: "Map", coverage: "Global", baseUrl: "https://s3.amazonaws.com/elevation-tiles-prod", auth: "none", license: "Mixed open sources (SRTM, GMTED, ETOPO1 …)", licenseUrl: "https://github.com/tilezen/joerd/blob/master/docs/attribution.md", commercialUse: "yes", attribution: "Terrain: Mapzen / AWS Open Data", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Static", featureState: "enabled", tier: 2 },
  { key: "esa_worldcover", provider: "ESA WorldCover (AWS Open Data)", dataset: "Global land cover 10 m, 2021 v200 (Cloud-Optimised GeoTIFF)", category: "Land cover", coverage: "Global", baseUrl: "https://esa-worldcover.s3.eu-central-1.amazonaws.com", auth: "none", license: "CC BY 4.0", licenseUrl: "https://esa-worldcover.org/en/data-access", commercialUse: "yes", attribution: "© ESA WorldCover project 2021 / Contains modified Copernicus Sentinel data (2021) processed by ESA WorldCover consortium", caching: "Allowed", redistribution: "With attribution", rateLimit: "Range requests, fair use", refresh: "Static (2021)", featureState: "enabled", tier: 1, notes: "Free replacement for Earth Engine / AlphaEarth land-cover composition. Read by window with geotiff.js; site composition only, screening grade." },
  { key: "jrc_gsw", provider: "JRC Global Surface Water", dataset: "Surface water occurrence 1984–2021 (30 m tiles)", category: "Water", coverage: "Global", baseUrl: "https://storage.googleapis.com/global-surface-water", auth: "none", license: "Copernicus / EC JRC free and open (CC BY 4.0 equivalent)", licenseUrl: "https://global-surface-water.appspot.com/download", commercialUse: "yes", attribution: "Source: EC JRC/Google (Pekel et al. 2016)", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Static (2021)", featureState: "enabled", tier: 2 },
  { key: "frankfurter", provider: "Frankfurter (ECB reference rates)", dataset: "Daily foreign-exchange reference rates", category: "Financial", coverage: "~30 currencies", baseUrl: "https://api.frankfurter.dev", auth: "none", license: "ECB reference rates, free reuse with source", licenseUrl: "https://frankfurter.dev", commercialUse: "yes", attribution: "Source: European Central Bank reference rates via Frankfurter", caching: "Allowed", redistribution: "With attribution", rateLimit: "Fair use", refresh: "Daily", featureState: "enabled", tier: 1, notes: "Benchmark normalisation; World Bank official rates cover other currencies." },
  { key: "mapillary", provider: "Mapillary (Meta)", dataset: "Street-level imagery coverage and images", category: "Map", coverage: "Global (crowd-sourced)", baseUrl: "https://tiles.mapillary.com", auth: "key", envVar: "MAPILLARY_TOKEN", license: "Imagery CC BY-SA 4.0; API terms of Mapillary", licenseUrl: "https://www.mapillary.com/terms", commercialUse: "yes", attribution: "Street imagery © Mapillary contributors", caching: "No", redistribution: "With attribution (CC BY-SA)", rateLimit: "Free token limits", refresh: "Continuous", featureState: "enabled", tier: 2, notes: "Free client token from mapillary.com/dashboard/developers. NOT CONNECTED until MAPILLARY_TOKEN is set." },
];
